### ISSUE TITLE
[NERSC] Installation of eazy package for TD analysis

### ISSUE THREAD

**Issue by alexandergagliano** [LSSTDESC/desc-help#101]
**Description**
Please install eazy package under $TD_SOFTWARE on perlmutter. Package is found at https://github.com/gbrammer/eazy-py/tree/master.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [X ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
The pip install is failing so far:
```
pip install eazy
Collecting eazy
  Downloading eazy-0.6.6.tar.gz (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 89.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
eazy depends on dust-attenuation@ git+https://github.com/karllark/dust_attenuation#egg=dust_attenuation
```
The developers seem to be aware of that 
```
# dustmaps needs healpy in environment.yml since
# often can't compile on Mac with pip
# ... removing requirement so that can distribute just with requirements.txt
# dustmaps
```

I'm guessing we need to do this install from source
```
git clone https://github.com/gbrammer/eazy-py.git

### Build the python code
cd eazy-py
pip install . -r requirements.txt

### Install and run the test suite, which also downloads the templates and
### filters from the eazy-photoz repository if necessary
pip install .[test] -r requirements.txt
pytest
```

Is this how you typically install this package?

**Comment by heather999** [comment]
I've gone ahead and installed eazy from source in the td_env-int  (integration) environment. most of the pytests have run successfully - so that's encouraging! One failed (out of 30) with:
```
FAILED eazy/tests/test_templates.py::test_template_smoothing - AttributeError: 'NoneType' object has no attribute 'flux'
```
I'm almost willing to believe this one test is out of date...

Maybe @alexandergagliano & @RickKessler  can try out the td_env integration environment and see that eazy works - then I can put this in the td_env dev version and ultimately we'll add this to the stable version.

**Comment by alexandergagliano** [comment]
Thanks @heather999! We've been iterating on this over the last few days and will follow up as soon as we can get a successful run going.

**Comment by heather999** [comment]
Hoping everything was fine - there is now a new release of td_env which includes eazy, this environment can be set up by doing:
source /global/cfs/cdirs/lsst/groups/TD/setup_td.sh 

Looking ahead, it would be nice to work with the developers and see if that issue with dustmaps can be fixed so we can use the distribution on PyPI
