### ISSUE TITLE
[NERSC] Pull w_2023_29 lsstsqre Docker->shifter image

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#102]
**Description**

Please make recent weekly available for LSST Science Pipelines at NERSC.  Specifically I'd like to be able to run

```
shifter --image=lsstsqre/centos:7-stack-lsst_distrib-w_2023_29
```

The current latest available is w_2023_21.  I need w_2023_29 to address DM-39484.  

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [X] Cori interactive command line
- [X] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Done!
In truth, any NERSC user can pull an image into shifter at NERSC and it is available for all to use.  So, whether I do it, or someone else, doesn't matter. Anyone can run:
shifterimg -v pull docker:lsstsqre/centos:7-stack-lsst_distrib-w_2023_29


If it we felt it was of interest, we could even pull the images each week via a cron job.  To my knowledge there is no space limit on us for shifter, but I still have this nagging concern about pulling in every weekly.

**Comment by wmwv** [comment]
Oh, thank you.  I now feel empowered for the future!

**Comment by wmwv** [comment]
I ran
```
shifterimg -v pull docker:lsstsqre/centos:7-stack-lsst_distrib-w_2023_44
```
all by myself today :)
