### ISSUE TITLE
[Github] Are there any quota limitations for github actions build servers?

### ISSUE THREAD

**Issue by mattkwiecien** [LSSTDESC/desc-help#103]
In the TJPCov repo, we want to modify our continuous integration to test python 3.8 and 3.11 on both linux and macOS systems.  This is 4 simultaneous build actions, each taking ~20 minutes.  This would happen when users submit PRs to our repo.  Before we switch to this new CI, we wanted to check to see if there were quotas / limitations for build server use within the LSSTDESC Github org?

**Comment by heather999** [comment]
HI @mattkwiecien Good question and thank you for reaching out! There are some usage limits outlined here: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
* 20 concurrent GitHub jobs are allowed - additional jobs will be queued.  Up to 5 concurrent MacOS jobs are allowed.
* Each job can run up to 6 hours.

Our GitHub plan allows us 3,000 Actions minutes/month, while we're in no danger of running over that right now we might want to think about how often our jobs run and for how long.  At this point, I'd say go ahead and feel free to run these jobs with your PRs - it sounds like exactly the type of CI we want to encourage. 

There are more specific limitations based on the type of runner you use: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by mattkwiecien** [comment]
Perfect - thank you for the resources and info @heather999 !
