### ISSUE TITLE
[NERSC] Need ENVs for ROMAN (for Roman-DESC project)

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#104]
**Description**
A clear and concise description of what the issue is.  

Analogous to 
echo $SNANA_LSST_ROOT
/pscratch/sd/d/desctd/cfs_mirror/SNANA/SURVEYS/LSST/ROOT

please define $SNANA_ROMAN_ROOT = /pscratch/sd/d/desctd/cfs_mirror/SNANA/SURVEYS/ROMAN/ROOT
in the td-setup, and same for $SNANA_ROMAN_USERS and $SNANA_ROMAN_SIM

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi @RickKessler - I'll follow up with a DM, but just want to check this is a request to slightly update the setup scripts for td_env to create some additional environment variables that point to new PSCRATCH areas that happen to be for the Roman-DESC work?  Sounds easy enough :)  I'll get that in and let you know so we can double check I have it right.

**Comment by RickKessler** [comment]
yes, above is correct.

**Comment by heather999** [comment]
done!
