### ISSUE TITLE
Has the DESC Portal page certificate expired?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#107]
When I go to 
https://lsstdesc-portal.nersc.gov
my browser warns me that the certificate has expired.  Is this the correct identification of the error?

Is this something that we should update or something we should has NERSC to do?

<img width="632" alt="Screenshot 2023-11-07 at 09 09 11" src="https://github.com/LSSTDESC/desc-help/assets/3201257/e105b346-d9ce-43d3-830e-f278bab91ed1">

**Comment by heather999** [comment]
Hi Michael,
That was the original and old URL for the DC2 data portal - but a few months later we moved to: https://data.lsstdesc.org/
NERSC kept up a redirect for a bit..  I can imagine that the cert for that has expired.
The DC2 data note was updated with the new correct URL. Are there other places still pointing to the old one?

**Comment by wmwv** [comment]
The Data Download page:

https://data.lsstdesc.org/doc/download

first sentence: "The [LSSTDESC Data Portal](https://lsstdesc-portal.nersc.gov/) allows anyone to transfer the DC2 Public Release data using Globus."

**Comment by wmwv** [comment]
That's the only reference in the git `lsstdesc.github.io` repo:

https://github.com/search?q=repo%3ALSSTDESC%2Flsstdesc.github.io%20lsstdesc-portal.nersc.gov&type=code

More broadly, here are the 12 places across 7-8 repos:

https://github.com/search?q=lsstdesc-portal.nersc.gov&type=code

**Comment by heather999** [comment]
ok - clearly some things to fix, some will require reaching out to individuals who have non-LSSTDESC repos

This repo: https://github.com/LSSTDESC/DC2-Public-Release  is archived and read-only.  We need to figure out if we want to revive it and fix this, at least that would be my vote - any opinions @yymao ?  

Starting a to do list

- [ ] DESC Public website lsstdesc.github.io
- [ ] LSSTDESC/DC2-Public-Release
- [ ] desc-data-portal
- [ ]  [lsst/rtn-001](https://github.com/lsst/rtn-001)
- [ ] [LSSTDESC/synth_cluster](https://github.com/LSSTDESC/synth_cluster)
- [ ] https://github.com/zonca/cmb-s4-data-portal
- [ ] https://github.com/abacusorg/abacussummit-data-portal
- [ ] [escape2020/school2021](https://github.com/escape2020/school2021)

**Comment by yymao** [comment]
I'd argue that we don't need to fix the URL in the archived DC2-Public-Release repo. The archived status is clearly marked with a date, and the README already links to the updated desc-data-portal repo. The old URL only appeared in more of the markdown file, so I would say the chance that people accidentally find it is very small.
