### ISSUE TITLE
[NERSC] Request to install a conda+pip environment for GPU use

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#109]
**Description**
A clear and concise description of what the issue is.  

I'd like to install the following environment:
```
conda create --name astrophot -c conda-forge python astropy cudatoolkit h5py \
  ipykernel jupyter matplotlib numpy pandas pyyaml pyarrow scipy requests tqdm \
  webbpsf
conda activate astrophot
pip install astrophot pyro-ppl torch
ipython kernel install --user --name=astrophot
```

to use for batch processing and testing through Jupyter Notebook usage against GPU nodes.

How do I create that environment to run on the GPU node.  When I create that environment on a login node, it doesn't work on a GPU node.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] jupyter terminal
- [x] Perlmutter interactive command line
- [ ] Batch jobs
- [x] python
- [ ] PSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi @wmwv 
As you've noticed the NERSC login nodes don't have the GPUs available and thus when you set up an environment, in most cases, that means you get the non-GPU version of some packages.  conda-forge has a blog about this with a potential workaround when you're installing from conda-forge: https://conda-forge.org/blog/2021/11/03/tensorflow-gpu/#installation
I'll admit I often get a little tangled up attempting to figure out what versions of cudatoolkit are available with the conda-forge distributions of pytorch though.

A quick way around this is to install the conda env from an interactive session on a GPU node.. I just did the following:
# Downloaded mambaforge
curl -LO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
# start up an interactive GPU session at NERSC:
salloc --nodes 1 --qos interactive --time 01:00:00 --constraint gpu --gpus 4 --account=m1727
 # install mambaforge
bash ./Miniforge3-Linux-x86_64.sh -b -p $PWD/py
source py/bin/activate
#install pytorch following the instructions on their website (https://pytorch.org/) for conda
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
# Testing that pytorch has GPU access from that same GPU interactive session
python
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

#in my case - that results in "cuda" being printed

Now you can go and add the other packages, but there's no need to install cudatoolkit - we can use the default cudatoolkit available at NERSC which is 12.2 right now.  So I went ahead did another mamba install (noting that webbpsf seems to require a pip install):
mamba install astropy h5py scipy requests tqdm matplotlib ipykernel jupyter pandas pyyaml pyarrow

Then I check that pytorch can still see the GPUs and it looks like it can.  After that I'd pip install webbpsf, pyro-ppl, and astrophot

**Comment by wmwv** [comment]
Thanks so much!

And yes, sorry.  webppsf` should have been under the `pip install` list not the `conda` one.

**Comment by wmwv** [comment]
I now find that the login nodes _do_ have GPUs.  I've tested that an environment created on a login node works on the login node, and the Jupyter kernel created from the environment works on a shared GPU Jupyter node.

**Comment by heather999** [comment]
Just adding this link here as a reference to note that indeed the Perlmutter login nodes have one GPU: https://docs.nersc.gov/systems/perlmutter/architecture/#login-nodes
