### ISSUE TITLE
[NERSC] Move from projecta to CFS

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#11]
**Description**
NERSC has approached us about migrating our projecta data to the Community File System.  

*Transition Date:  April 22, 2020*

All projecta data under `/global/projecta/projectdirs/lsst/` will be moved to: `/globala/cfs/cdirs/lsst/projecta`

We will then have 3 PB under `/global/cfs/cdirs/lsst` until our 1 PB lease on projecta expires on 1 May 2023

- [x] Announce on #desc-nersc and #desc-co 
- [x] Inform All Working Groups of this transition
- [ ] GCRCatalogs
    - [X] Set up a new /global/cfs/cdirs/lsst/catalogs area  This will be the new ROOT_DIR.
    - [x] Contact current WG owners of those catalogs
    - [ ] Update desc-python and desc-stack to use the next GCRCatalogs release 0.16.0
- [x]  DESCQA
    - [x] Update v1 code to point to new catalog locations 
    - [x] Update v2 to use ROOT_DIR in GCRCatalogs 
    - [x] Migrate www area
- [x] /global/projecta/projectdirs/lsst/www areas
    - [x] Contact all current WWW owners to inform them of the transition.
     Details about Science Gateways](https://docs.nersc.gov/services/science-gateways/)
- [ ] DC2 SQLIITE tracking DB
    - [ ] Will need to be updated with the new paths for all tracked files (affects Run2.1, Run2.1.1, and Run2.2)
    https://github.com/LSSTDESC/ImageProcessingPipelines/issues/143

**Comment by heather999** [comment]
Closing this but will open a new issue specific to the sqlite tracking dbs

**Comment by johannct** [comment]
it is not closed :)
