### ISSUE TITLE
Urgent problem finding Python.h with setup_td on Perlmutter

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#112]
**Description**
A clear and concise description of what the issue is.  

using setup_td (default or dev), cannot make SNANA codes on Perlmutter due error finding Python.h

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

cd $SNANA_DIR/src
make 
...
results in failure with
../src/genmag_PySEDMODEL.c:74:11: fatal error: Python.h: No such file or directory
   74 | #include  <Python.h>

**Screenshots**

**Comment by heather999** [comment]
Discussed via DM on Slack.
Trying again on a fresh login node on Perlmutter
```
source $CFS/lsst/groups/TD/setup_td.sh -g
cd $SNANA_DIR/src
make clean
make
```
The above worked. I also checked that the environment has Python.h it's in $CONDA_PREFIX/include/python3.11.  It turns out that the issue was a previous conda env set up in the same session.
