### ISSUE TITLE
[NERSC] Changing files assigned to the "desc" user back to my ownership

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/desc-help#115]
**Description**
I seem to have re-assigned ownership of the NERSC files here:
`/global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/`
to the `desc` user instead of myself (username `zuntz`). Would it be possible to change them back so I can update them?

This could be done with
`chown -vR zuntz /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/`

by the desc user.

Thanks!
Joe

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Perlmutter interactive command line
- [ ] Batch jobs
- [ ] GPU nodes
- [ ] python
- [ ] PSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. `ls -l /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/*`

**Comment by joezuntz** [comment]
Looks like we have a spam commenter here.

**Comment by joezuntz** [comment]
Thanks! I've done the immediate update I wanted to do. Can you remove the ACL now, since we would like to use that directory for relatively disc-intensive work?

And in the long run option 2 would be good (with the -R flag for recursive I guess).

**Comment by heather999** [comment]
ACLs have been removed!  
I'll open the ticket with NERSC

**Comment by heather999** [comment]
This appears to be fixed!
