### ISSUE TITLE
lsst.sims packages missing from desc-python and desc-stack

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#13]
I believe previous versions of desc-python and desc-stack included the lsst.sims packages, which are now no longer present.  This causes errors in some notebooks, such as my deredden MW dust notebook
https://github.com/LSSTDESC/DC2-analysis/blob/u/sschmidt23/mwdust/contributed/Deredden_MW_dust.ipynb

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

To Reproduce in JupyterLab:
1. Load notebook with desc-stack or desc-python kernel
2. try to import with packages with, e.g. :

`from lsst.sims.catUtils.dust import EBVbase`
`from lsst.sims import photUtils`
`from lsst.sims.photUtils import BandpassSet`
4. This raises  `ModuleNotFoundError: No module named 'lsst' ` error. 

**Screenshots**

**Comment by heather999** [comment]
Hi @sschmidt23 It's been too long, but now with more recent DMstacks moving to conda-forge and some fixes in the sims builds  - we have new conda environments available that now provide stack+sims:
```
desc-stack-weekly
desc-stack-weekly-latest
```
There is also `desc-python-bleed` which is stack-free, but pulls in the latest releases of all packages like CCL, NaMaster, etc

People will have to re-run some set up to gain access to these at NERSC, just once you would do:
```
source /global/common/software/lsst/common/miniconda/kernels/setup.sh
```
I have run your `Deredden_MW_dust.ipynb` using `desc-stack-weekly` and it seems to complete and puts up plots
Some of this was just posted: [https://lsstc.slack.com/archives/C2U2K05JR/p1592407555153100](https://lsstc.slack.com/archives/C2U2K05JR/p1592407555153100)
