### ISSUE TITLE
[NERSC] Set up CFS organization

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#14]
**Description**
Now that the Community File Space is ready, we need to properly organize the directory hierarchy, set up permissions, and reorganize our existing data files.

**Comment by joezuntz** [comment]
I have a few things in $CFS/lsst/www/txpipe, but I'm happy for them to be moved anywhere - just let me know and I can update any relevant links.

**Comment by heather999** [comment]
Hi @joezuntz the $CFS/lsst/www area is permanent and our new home so it sounds like you are already in the right spot.  Things under `/global/projecta/projectdirs/lsst/www` would need to be moved though - but I don't see anything owned by you in that area. Looks like you're good to go!

**Comment by heather999** [comment]
Things have progressed.  
* The proposed structure is explained in [this doc](https://docs.google.com/document/d/1AHxQnjcD61BoM2qTe6yZI3UTMSVxgWIp0mFjd7U04zA/edit?usp=sharing).
* NERSC will migrate the WG areas to their new homes in `/global/cfs/cdirs/lsst/groups`
* Data has been copied to the new `/global/cfs/cdirs/lsst/shared` area
* Joanne and Yao are updating GCRCatalogs configs to use the new data locations and updated ROOT_DIR (at NERSC: `/global/cfs/cdirs/lsst/shared`)
* Yao has migrated all remaining `projecta/www` areas to the new `cfs/www` area and made sure the old projecta URL continue to work

**Comment by heather999** [comment]
Think this is done (and has been for awhile)
