### ISSUE TITLE
[NERSC] Moving new Buzzard catalogs to CFS

### ISSUE THREAD

**Issue by j-dr** [LSSTDESC/desc-help#15]
**Description**
I would like to move a set of new Buzzard catalogs to the new CFS space. Right now there is one new catalog on top of the catalog that lives in the old lsst project space. This new catalog is in my scratch space in the following two directories: `/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/addgalspostprocess/truth/` and `/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/surveymags/`

I am planning on releasing a few more of these, so if they can be moved into a directory with the structure `/global/cfs/cdirs/lsst/shared/external/Buzzard/Buzzard-<num>/v2.0.0/{truth,surveymags}` (as per the suggestion of @heather999 in a private slack message) that would be ideal. In this case, `<num>=4`. 

Thanks a bunch and let me know if there is anything I can do to help!

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Just want to make sure I have this correct
We'll copy:
`/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/addgalspostprocess/truth/` into
`/global/cfs/cdirs/lsst/shared/external/buzzard/Buzzard-4/addgalspostprocess/truth`
and
`/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/surveymags/` into
`/global/cfs/cdirs/lsst/shared/external/buzzard/Buzzard-4/surveymags`

Look good @j-dr ?

**Comment by j-dr** [comment]
Would you mind copying `/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/addgalspostprocess/truth/` to `/global/cfs/cdirs/lsst/shared/external/buzzard/Buzzard-4/truth` instead? Other than that, looks good!

**Comment by heather999** [comment]
sorry.. I even knew that from your original message!  and I see I also omitted the `v2.0.0`  so..  I'll try again
`/global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/addgalspostprocess/truth/`
to
`/global/cfs/cdirs/lsst/shared/external/buzzard/Buzzard-4/v2.0.0/truth`

and similarly
`global/cscratch1/sd/jderose/BCC/Chinchilla/Herd/Chinchilla-4/surveymags/`
to 
`/global/cfs/cdirs/lsst/shared/external/buzzard/Buzzard-4/v2.0.0/surveymags`

sorry for the confusion @j-dr  I need to slow down :)

**Comment by j-dr** [comment]
Looks good, thanks!

**Comment by heather999** [comment]
Globus transfer completed - file integrity checking was turned on and there were no errors.

Just let me know if anything looks incorrect!

**Comment by yymao** [comment]
This has been done.
