### ISSUE TITLE
Rename baseDC2_5000 catalogs to base_5000

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#16]
As discussed on Slack, while we are working on reorganizing the catalogs for use at NERSC and other sites, it was decided the `baseDC2_5000` name could be improved.  These catalogs will be stored under: `shared/extragalactic/skysim` and the working plan is to rename them to `base_5000`.
See Slack: https://lsstc.slack.com/archives/CB30ND9CG/p1588960949091000?thread_ts=1588890311.086700&cid=CB30ND9CG
and
https://lsstc.slack.com/archives/CB4LA1SBS/p1589037178007200

**Comment by evevkovacs** [comment]
I'm going to use `base5000` unless anyone has a strong objection

**Comment by evevkovacs** [comment]
@yymao @heather999 PR submitted in gcr-catalogs

**Comment by yymao** [comment]
This has been done. Closing. (cc @JoanneBogart)
