### ISSUE TITLE
[NERSC] error loading MAF

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#17]
**Description**
I am suddenly having trouble loading LSST MAF; it was working find last night. Specifically, I used to the run the following:
```
awan@cori13: source /global/common/software/lsst/cori-haswell-gcc/stack/setup_current_sims.sh

bash: /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/loadLSST.bash: No such file or directory

Now setup any necessary stack packages such as: setup -t w_2019_19 lsst_distrib or setup -t sims_w_2019_19 lsst_sims

awan@cori13:: setup sims_maf_contrib -r /global/homes/a/awan/LSST/lsstRepos/sims_maf_contrib

If 'setup' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf setup
```
I am not sure what has changed but I don't remember seeing the bash error before. I also tried loading the `lsst` kernel in `jupyter` and importing an LSST MAF object (via `import lsst.sims.maf.db as db`) but I get an error saying `ModuleNotFoundError: No module named 'lsst'.`

I have tried to look for documentation re `loadLSST.bash` but without luck. I'd really appreciate some help.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
Please see above.

**Comment by humnaawan** [comment]
okay I just found the [confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/NERSC+Software+Installations) where it mentioned `loadLSST.bash`.

**Comment by heather999** [comment]
Hi @humnaawan I think I know the problem.. this dev version of sims was removed from CVMFS.  Let me update the scripts for `setup_current_sims.sh` and that should fix the issue.  Be back in a bit.

**Comment by humnaawan** [comment]
thank you!

**Comment by heather999** [comment]
Hi @humnaawan I moved `setup_current_sims.sh` to point to `w_2020_05` which is available on CVMFS and is before some of the most recent updates to DMstack that I'm not quite ready to deal with :)  This is a more recent sims than what you were working with - so there may be some changes in the code.  Please give this another try, in a fresh bash shell, and let me know how it goes.

**Comment by humnaawan** [comment]
okay i'm able to load MAF! thanks so much.
