### ISSUE TITLE
[NERSC] Copy redMaPPer catalogs to shared cfs space

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#18]
**Description**
In order to implement https://github.com/LSSTDESC/gcr-catalogs/pull/454 all the `redmapper` catalogs need to be copied from `/global/cscratch1/sd/erykoff/redmapper_staging` to `/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmapper_v1.1.4`

**Comment by heather999** [comment]
Hi @erykoff  Looks like an easy request to fulfill, just one question. We have this area already:
```
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmapper_v1.1.4> ls -l
total 33472
-rw-r-----+ 1 desc lsst  3116160 Jan 16  2019 cosmoDC2_v1.1.4_run_redmapper_v0.2.1py_lgt20_catalog.fit
-rw-r-----+ 1 desc lsst 31129920 Jan 16  2019 cosmoDC2_v1.1.4_run_redmapper_v0.2.1py_lgt20_catalog_members.fit
```

Should the files under `/global/cscratch1/sd/erykoff/redmapper_staging` just be added to this area, and we retain the two existing files?

**Comment by erykoff** [comment]
Yes, we should leave the old version there (as they are based on the same underlying cosmoDC2 1.1.4 data), but the linked ticket will deprecate those.

**Comment by heather999** [comment]
@erykoff  Sorry, I need group access to those files `chgrp lsst`  so I can copy them:

```
ls -l /global/cscratch1/sd/erykoff/redmapper_staging
total 28712
-rw-r----- 1 erykoff erykoff  2548800 Jun  1 14:07 cosmoDC2_v1.1.4_run_redmapper_v0.5.7_lgt20_catalog.fit
-rw-r----- 1 erykoff erykoff 26841600 Jun  1 14:07 cosmoDC2_v1.1.4_run_redmapper_v0.5.7_lgt20_catalog_members.fit
```

**Comment by erykoff** [comment]
Done.  Sorry about that, checked the path but not the files!

**Comment by heather999** [comment]
Thanks - Done!
