### ISSUE TITLE
Copy files for photo-z add on catalog for run2.2i_dr6a

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#19]
I've created a new reader for a photo-z add on catalog for dc2_object_run2.2i_dr6a (see gcr-catalogs issue [#462](https://github.com/LSSTDESC/gcr-catalogs/issues/462)  for details).
I do not have write permission to move the relevant parquet files to the /global/cfs/cdirs/lsst/shared/... directory, so I need someone with permissions to copy the 78 parquet files currently in:
`/global/cfs/cdirs/lsst/groups/PZ/PhotoZDC2/run2.2i_dr6_test/outputs/finished`
to a newly created subdirectory:
`/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/photoz/dr6`

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
@sschmidt23 the 78 parquet files have been copied to the new directory: `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/photoz/dr6`

**Comment by sschmidt23** [comment]
Thanks, looks like everything is working, so I'll close this issue.
