### ISSUE TITLE
[NERSC] Test and Deploy a JupyterHub kernel that reliably can use ipympl + afwdisplay

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#2]
**Description**
I would like to be able to support interactive image viewing using the `lsst.afw.display` Science Pipelines functionality with an `ipympl` backend.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. Check out on NERSC
git clone https://github.com/lsst/display_matplotlib
2. Log in to NERSC Jupyter Hub
3. Open the `examples/display_matplotlib.ipynb` Notebook in the `display_matplotlib` directory checked out above.
4. Select `desc-stack` kernel.
4. Run Cells.
One should see the random image created in the previous cell.

Instead I get the following error message
```
Error displaying widget: model not found
```

**Comment by wmwv** [comment]
The following `matplotlib` issue may be relevant:

https://github.com/matplotlib/jupyter-matplotlib/issues/112

**Comment by heather999** [comment]
Started to take a look at this.  I see that NERSC's jupyter environment already includes the `@jupyter-widgets/jupyterlab-manager` and `jupyter-matplotlib` extensions.  I do see that ipympl in `desc-stack` is an older release, I'll try updating and see if that helps.

**Comment by heather999** [comment]
Upgrading ipympl seems to have fixed it.  @wmwv Can you try `desc-stack-dev` with the `display_matplotlib.ipynb` and see that things generally run?  I see just one error message `The module://ipympl.backend_nbagg matplotlib backend doesn't support display._getEvent()` but the plots seem to come up. 
If it looks good, I'll promote this to prod and `desc-stack` will be properly updated.

**Comment by wmwv** [comment]
Yes, `desc-stack-dev` works.  Thank you!

**Comment by heather999** [comment]
Sorry for the delay, `desc-stack` has just been updated.  Closing this issue, but if any problems come up, feel free to re-open or start a new issue.
