### ISSUE TITLE
[CONFLUENCE] This is a reminder to setup a page describing the various environments that are available to people with some use cases or examples to help them navigate the options. I am happy to help read the page for clarity etc. but am not the best person to try writing it. 

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/desc-help#20]
**Description**
A clear and concise description of what the request or problem is.

**Screenshots**

**If applicable, please indicate your Browser by placing an X between the [ ]**
 - [ ] Chrome
 - [ ] Firefox
 - [ ] Internet Explorer
 - [ ] Microsoft Edge
 - [ ] Opera
 - [ ] Safari
 - [ ] Other

**Comment by yymao** [comment]
A confluence page that documents DESC environments is available at https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+Environments
