### ISSUE TITLE
Copying files from cscratch directory to CFS for new photo-z xgal reader

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#21]
I've created a new reader for a set of machine learning photo-z's for a subset of the extragalactic catalog.  The 393 parquet files for this dataset currently live at:
`/global/cscratch1/sd/schmidt9/CosmoDC2v114_image/FlexZPipe/outputs`
(all files named *.parquet, the *.hdf5 are **not** necessary).  These files need to be copied to a new directory:
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/photoz_v1.1.4/FlexZBoost/

Permissions should be set such that group members can read the cscratch files for copying.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Hi @sschmidt23 Will do - I just need read permissions to be granted on: `/global/cscratch1/sd/schmidt9/CosmoDC2v114_image/FlexZPipe/outputs`

**Comment by sschmidt23** [comment]
Ah, I forgot you need execute privilege on the folder to copy, just changed, I think you should be ok to copy now.

**Comment by heather999** [comment]
Sorry @sschmidt23 I still can't access that area.  I think you need to allow at least `x` all the way down starting from:
```
# file: global/cscratch1/sd/schmidt9/
# owner: schmidt9
# group: schmidt9
user::rwx
group::---
other::---
```

I can't see the permissions below the top level of your CSCRATCH area, so I'm not quite sure what it's set to right now.

We could think about setting up a dedicated directory under your CSCRATCH area that grants access to the `lsst` group

**Comment by sschmidt23** [comment]
Ugh, I forgot to set the permissions on my parent directory, it should be set to group read and execute  now all the way down to the files output directory.  Sorry about that.

**Comment by heather999** [comment]
sorry - i still can't get in to copy, I can see this - maybe group needs to be set to `lsst`?
```
getfacl: Removing leading '/' from absolute path names
# file: global/cscratch1/sd/schmidt9/CosmoDC2v114_image/
# owner: schmidt9
# group: schmidt9
user::rwx
group::rwx
other::---

ls /global/cscratch1/sd/schmidt9/CosmoDC2v114_image/FlexZPipe/outputs
ls: cannot access '/global/cscratch1/sd/schmidt9/CosmoDC2v114_image/FlexZPipe/outputs': Permission denied
```

**Comment by heather999** [comment]
Hi @sschmidt23 The 393 parquet files have been copied to the new directory: `/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/photoz_v1.1.4/FlexZBoost`  Just let me know if there are any problems!

**Comment by sschmidt23** [comment]
I tested the new path and everything works, so closing this issue.
