### ISSUE TITLE
Copying files from groups/PZ to CFS to add a new column

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#22]
As a solution to a composite catalog loading problem, I've added a new `photoz_mask` column to one of the existing catalogs.  I created new pandas hdf5 files with this new column included, and these new files need to be copied from directory:
/global/cfs/cdirs/lsst/groups/PZ/PhotoZDC2/COSMODC2v1.1.4/IMAGE/10_year_error_estimates
to 
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/photoz_v1.1.4/IMAGE/10_year_error_estimates/
There are 393 new files which have names in the format `z_{}_{}.step_all_withmask.healpix_{}_magwerr.h5` (note the "withmask").  

These will replace the files that are already in the `shared` directory.  We can delete the previous version of the  files currently residing in that directory in the near future, once an update is pushed to gcr-catalogs, and then that update gets propagated to the desc kernels.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Done - thanks for the very clear instructions!  Just let me know if there are any problems.

**Comment by sschmidt23** [comment]
Reader works with new path, so everything copied correctly, thanks!
