### ISSUE TITLE
Upgrade the matplotlib to version 3.2.1 for desc-dia kernel

### ISSUE THREAD

**Issue by shuliu2017** [LSSTDESC/desc-help#24]
**Description**
As discussed [here](https://lsstc.slack.com/archives/CJFR141PY/p1593032501216000), to display multiple post stamps in the same row of Jupyter notebook using `desc-dia` kernel, we need the `3.2.1` version of `matplotlib`. 

Testcase:

```
afwDisplay.setDefaultBackend('matplotlib')
fig, ax = plt.subplots(1, 3, figsize=(9, 4))
display = []
plt.sca(ax[0])
display.append(afwDisplay.Display(frame=fig))
display[0].scale("linear", "zscale")
display[0].mtv(exposure)
plt.sca(ax[1])
display.append(afwDisplay.Display(frame=fig))
display[1].scale("asinh", "zscale")
display[1].mtv(exposure)
plt.sca(ax[2])
display.append(afwDisplay.Display(frame=fig))
display[2].scale("linear", min=0, max=10)
display[2].mtv(exposure)
```

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
HI @shuliu2017 This brings up a question about the `desc-dia` kernel. There have been other notes about this environment such as: https://lsstc.slack.com/archives/CJFR141PY/p1586198462035900?thread_ts=1585671475.008600&cid=CJFR141PY

I have not been actively keeping this environment up to date and initially thought this [might be a temporary environment](https://lsstc.slack.com/archives/CJFR141PY/p1563452624057900) - but I am happy to revisit that.  The process to create the environment is  a lot more automated now.  I would just need to know what the DIA group would prefer be included in such a conda environment.  We could
*  Tag this current version and then look into setting up a new environment
*  This new environment would likely move to a more recent DM weekly and version of obs_lsst 

About updating matplotlib in this particular environment - I can take a look and give it a try - I'm just hesitating as this environment uses an old DMstack which dictates the versions of various packages.

 @BrunoSanchez @rearmstr @wmwv   I'll go dig up what we have in this environment now, and perhaps you guys can let me know what would be best for the DIA group?

**Comment by BrunoSanchez** [comment]
Hi @heather999 and @shuliu2017, getting this up to date is an excellent idea taking into account that the next DESC meeting is coming in few weeks.
Let me check about this, because I have not been using `desc-dia` for a while now, I am mostly using the _shared_ DIA stack that is available at the shared space.

Probably @rearmstr can quickly give (again, sorry for repeating this question so often) a more detailed description on the latest master of `dia_pipe` and its compatibility with most recent builds of the DM stack. 

In any case I will raise this to `desc-dc2-dia` channel, to get this ready.

**Comment by heather999** [comment]
@BrunoSanchez I'm going to close this as I believe the shared environment we have set up at NERSC for SN takes care of this.  Please feel free to open a new issue though if we still need to provide something for DIA.
