### ISSUE TITLE
[NERSC] Update pyarrow version to at least 0.13.1 (current 0.17.1 would be fine)

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#25]
**Description**

Please update pyarrow version to at least 0.13.1 in `desc-python` and `desc-stack`.  The current version 0.17.1 would be ideal.  This is necessary for reading the DPDD Parquet files in Dask.

Choose all applicable topics by placing an 'X' between the [ ]:
- [X] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

```
import dask.dataframe as dd
datafile = "/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/dc2_object_run2.2i_dr6.parquet"
df = dd.read_parquet(datafile, columns=['ra', 'dec', 'mag_g', 'mag_r', 'mag_i',
                                        'magerr_g', 'magerr_r', 'magerr_i', 'extendedness'],
                     engine='pyarrow')
```

**Screenshots**

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-b4a0ee6d93bf> in <module>
      3 df = dd.read_parquet(datafile, columns=['ra', 'dec', 'mag_g', 'mag_r', 'mag_i',
      4                                         'magerr_g', 'magerr_r', 'magerr_i', 'extendedness'],
----> 5                      engine='pyarrow')

/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, chunksize, **kwargs)
    208 
    209     if isinstance(engine, str):
--> 210         engine = get_engine(engine)
    211 
    212     if hasattr(path, "name"):

/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in get_engine(engine)
    498 
    499         if LooseVersion(pa.__version__) < "0.13.1":
--> 500             raise RuntimeError("PyArrow version >= 0.13.1 required")
    501 
    502         _ENGINES["pyarrow"] = eng = ArrowEngine

RuntimeError: PyArrow version >= 0.13.1 required
```

**Comment by heather999** [comment]
Working on updating desc-python and looking at desc-stack now. 
Just note that all the most recent releases of packages including pyarrow, dask, etc are available in `desc-python-bleed` Quickly testing your kind snippet with the `desc-python-bleed` kernel works.

**Comment by wmwv** [comment]
> Just note that all the most recent releases of packages including pyarrow, dask, etc are available in desc-python-bleed 

Oh, right.  Thank you!  I hadn't fully internalized that `desc-python-bleed` had the latest versions of _all_ packages.  That's great.

**Comment by heather999** [comment]
Concerning `desc-stack`, DM v19 is pinned at pyarrow==0.13.0.  I do not see any 0.13.1 available, rather there is a jump to 0.14.0 https://pypi.org/project/pyarrow/0.13.0/#history
The latest DMstack weekly is on pyarrow 0.16.0.  Given that this request is for reading DPDD files, to support Run2.2i which was processed with DMstack v19 - I could try an update and make a special desc-stack with updated pyarrow and dask, so we can see that it generally works - but I'll keep desc-stack as is so it is consistent with v19.
Soon there will also be a desc-stack for v20 which at least will have pyarrow 0.16.0 and conda-forge packages - so that might make this a bit easier to manage.

**Comment by wmwv** [comment]
Ah, thanks for the explanation and the investigation.  I agree with leaving `desc-stack` as it is at `version(pyarrow)==0.13.0`.

**Comment by heather999** [comment]
`desc-python` has now been updated to 0.17.1, however as mentioned by Julien P: https://github.com/LSSTDESC/desc-python/issues/53#issuecomment-660854650 I am considering downgrading to 0.15.1
