### ISSUE TITLE
[NERSC] Update `dask` and `distributed` to `2.18.0`

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#26]
**Description**

Update `dask` and `distributed` to `2.18.0` from current `2.15.0` and `2.15.1`.

This will match the default Dask cluster worker configuration

Choose all applicable topics by placing an 'X' between the [ ]:
- [X] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. Launch JupyterHub session on NERSC.
2. Launch Dask workers from JupyterHub tabs on left.
3. Open Notebook with `desc-python` kernel.
4. Start up connection to Dask cluster from Notebook:
```
from dask.distributed import Client
scheduler_address = "tcp://127.0.0.1:39447"
client = Client(address=scheduler_address)
```

**Screenshots**
Output will warn of:
```
/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/site-packages/distributed/client.py:1079: VersionMismatchWarning: Mismatched versions found

+-------------+--------+-----------+---------+
| Package     | client | scheduler | workers |
+-------------+--------+-----------+---------+
| cloudpickle | 1.4.0  | 1.4.1     | 1.4.1   |
| dask        | 2.15.0 | 2.18.0    | 2.18.0  |
| distributed | 2.15.1 | 2.18.0    | 2.18.0  |
| numpy       | 1.18.1 | 1.17.2    | 1.17.2  |
+-------------+--------+-----------+---------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

I don't think there's any good reason to downgrade `numpy` (and many reasons not to).  By updating `dask` and `distributed` seems worthwhile.

**Comment by wmwv** [comment]
This issue can be bundled with #25 in implementation of the updates.

**Comment by wmwv** [comment]
@heather999 Can you add `dask-mpi` to `desc-python-bleed`?

**Comment by heather999** [comment]
Sure - and just one question.  In `desc-python-bleed`, dask and friends on on 2.20.0  - is that a problem and should be pinned back to 2.18.0?  or is it ok?

**Comment by wmwv** [comment]
`2.20.0` is fine.

**Comment by heather999** [comment]
* desc-python-bleed now has dask-mpi and should be all set
* desc-python-dev has been updated to pyarrow 0.17.1, dask 2.18.0 and distributed 2.18.0
* I'm having some trouble with desc-python that I need to sort out.
* I'll add dask-mpi to the next iteration of desc-python

**Comment by wmwv** [comment]
Ah, sorry one more.  Can you also add `dask_jobqueue` to `desc-python-bleed`?

**Comment by heather999** [comment]
Done - I just updated desc-python-bleed at NERSC.

**Comment by heather999** [comment]
`desc-python` has been updated at NERSC. The full list of current versions is listed here and should include all the dask updates and additions: https://github.com/LSSTDESC/desc-python/blob/v0.0.31/conda/desc-python-env-nersc-export.yml
