### ISSUE TITLE
[NERSC] Move DC2 DR6a matched catalog to cfs?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/desc-help#28]
**Description**
I have created a set of DC2 DR6a matched catalogs that live in `'/global/cscratch1/sd/jsanch87/DC2_Run2.2i/matched_ids_dc2_object_run2.2i_dr6a_*.fits.gz'` (78 fits files). I think that, it'd be good if we moved them to `cfs`. Should I do this myself or would you prefer to move them @heather999?

Thanks in advance!!

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [X] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
I'm happy to make a copy, we just need to come to agreement on where these files should go. Pinging @yymao and @JoanneBogart   Right now I'd copy into:
`/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/Run2.2i-dr6a/matched`  Though in other runs it looks like we just stored all the matched files under `addons`.

**Comment by yymao** [comment]
@heather999 how about `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/matched/dr6a` to match what photoz is using?

**Comment by fjaviersanchez** [comment]
Thanks a lot!

**Comment by heather999** [comment]
Transfer is done, 78 files are now in `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/matched/dr6a` - just let me know if there's any problems.

**Comment by yymao** [comment]
Thanks @heather999 !

@fjaviersanchez can you update the path in https://github.com/LSSTDESC/gcr-catalogs/pull/472 ? And then I'll approve and merge. Thanks!
