### ISSUE TITLE
[NERSC] Request to copy Run2.2i DR6c data to shared space

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-help#29]
**Description**
Request to copy

`/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/run2.2i-wfd-dr6-pre-release`

to 

`/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/dpdd/Run2.2i-dr6c`

for upcoming Run 2.2i dr6c release in GCRCatalogs. Thanks!

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [x] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
n/a

**Screenshots**
n/a

**Comment by heather999** [comment]
Both the object cats and metacal cats are now in: `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/dpdd/Run2.2i-dr6c`  Just let me know if there are any problems.

**Comment by yymao** [comment]
Thank you @heather999. Works as expected.
