### ISSUE TITLE
[NERSC] Add `selenium` to `desc-python`

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#30]
**Description**

@heather999 Could you add `selenium` to the Python packages in `desc-python`.  This package is required to save output plots from HoloViews using the `bokeh` backend, even though it isn't explicitly a requirement of HoloViews.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. Go to at JupyterHub notebook
2. Click on `desc-python`or `desc-python-bleed`
3. Run
```
import holoviews as hv
hv.extension('bokeh')

foo = hv.Points(([1, 2], [3, 4]))
hv.save(foo, 'test.png')
```
```
RuntimeError: To use bokeh.io image export functions you need selenium ('conda install selenium' or 'pip install selenium')
```

**Comment by heather999** [comment]
@wmwv selenium is now included in `desc-python` and `desc-python-dev`.  I'm having a little problem updating `desc-python-bleed` - unrelated to this package.  Need to fix that before I can update a new desc-python-bleed at NERSC.

**Comment by heather999** [comment]
selenium is now in desc-python-bleed as well.  Closing this issue, but just let me know if you have any problems with this.
