### ISSUE TITLE
[NERSC] Move DC2 DR6c matched catalog to cfs?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/desc-help#32]
**Description**
A clear and concise description of what the issue is.  

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

Issue similar to #28 but now with DR6c. I created the matched catalogs for dr6c and they live at `/global/cscratch1/sd/jsanch87/DC2_Run2.2i/matched_ids_dc2_object_run2.2i_dr6c_*.fits.gz`. Would it be possible to transfer them to cfs? I guess that they would live at `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/matched/dr6c`

**Comment by fjaviersanchez** [comment]
Let's pause this for a bit because I just saw there were problems with some of the tracts so I think I'm going to rematch the catalogs.

**Comment by fjaviersanchez** [comment]
Ok, I just fixed it. One of the files was corrupt at the time of compressing but I just remade it. They all now look good to go!

**Comment by heather999** [comment]
Thanks @fjaviersanchez I've been out for the past few days.  I just completed the copy of 165 files into: `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/matched/dr6c`

**Comment by fjaviersanchez** [comment]
Thanks a lot @heather999!!
