### ISSUE TITLE
[NERSC]

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#37]
We added another reader for a subset of cosmoDC2_v1.1.4_small data to GCRCatalogs, we need to have one file copied to the shared area of CFS. 
Could you please copy the file:
/global/cfs/cdirs/lsst/groups/PZ/PhotoZDC2/COSMODC2v1.1.4/10_year_error_estimates/OLIVIA_WORK/final-result.parquet
to 
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/photoz_v1.1.4/10_year_error_estimates/OLIVIA_WORK/final-result.parquet
(you will need to create the `OLIVIA_WORK` subdirectory).

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by JoanneBogart** [comment]
@heather999 is on vacation this week.  I also have permission to write to the shared area and can do the copy tomorrow morning (Friday) if you like.

**Comment by sschmidt23** [comment]
That would be great, thanks @JoanneBogart  !

**Comment by JoanneBogart** [comment]
Done.

**Comment by sschmidt23** [comment]
File has been copied and reader works, closing, thanks!
