### ISSUE TITLE
[NERSC] Add Ceci to the jupyter desc-stack environment

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/desc-help#38]
**Description**
Please could you add Ceci to the desc-stack?  It can be installed from pypi and is at version 1.0.4

Choose all applicable topics by placing an 'X' between the [ ]:
- [X ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Great - I'll add it in and see what happens.  Would it be useful to also include Ceci in `desc-python`?

**Comment by joezuntz** [comment]
Hi Heather,

Thanks - that would be useful too.

Cheers,
Joe

**Comment by heather999** [comment]
Hi Joe, I'll add ceci to desc-stack while adding the upcoming GCRCatalogs tag that should come out today.
`desc-python`, `desc-python-dev` now have ceci installed
`desc-python-bleed` will include it with the upcoming GCRCatalogs tag - so hopefully by tomorrow.

**Comment by heather999** [comment]
Hi @joezuntz All environments have been updated to include ceci.  There are now updated versions of both `desc-stack` and `desc-python`   Please let me know see any issues with ceci in these environments.

**Comment by heather999** [comment]
Closing - hoping things are ok, feel free to open a new issue if there are problems going forward!
