### ISSUE TITLE
[NERSC] Copy suprême survey property maps to shared storage

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#39]
**Description**
Copy `suprême` survey property maps to shared storage.

The survey property maps for grizy bands for DC2 DR6d (now DR6) were run in my scratch space and are in:

`/global/cscratch1/sd/erykoff/dc2_dr6/supreme/supreme_dc2_dr6d_v3_*.hs`.

These should be transferred to the appropriate shared space for DC2 DR6 auxiliary data.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [x ] CSCRATCH
- [ x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Just want to confirm with @JoanneBogart and @yymao - I'm planning to copy these supreme maps to:
`/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/supreme/dr6-wfd` where we can add the u band when they become available.

**Comment by JoanneBogart** [comment]
@heather999 sounds right to me

**Comment by erykoff** [comment]
Following up on this, the `u`-band maps are now available from the same directory.  Please let me know when the transfer is done and I can add a listing to the maps in GCR.

**Comment by heather999** [comment]
Hi @erykoff I just need lsst group access granted on those u-band files like:
```
-rw-rw---- 1 erykoff erykoff 627105600 Sep 22 08:30 /global/cscratch1/sd/erykoff/dc2_dr6/supreme/supreme_dc2_dr6d_v3_u_psf_e1_wmean.hs
```

**Comment by erykoff** [comment]
Oops!  Try it now, please.

**Comment by heather999** [comment]
Great!  copy finished.  There are 11 files:
```
/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/supreme/dr6-wfd> ls supreme_dc2_dr6d_v3_u*
supreme_dc2_dr6d_v3_u_airmass_wmean.hs
supreme_dc2_dr6d_v3_u_bgmean_wmean.hs
supreme_dc2_dr6d_v3_u_boresight_dist_wmean.hs
supreme_dc2_dr6d_v3_u_coadd_mask_or.hs
supreme_dc2_dr6d_v3_u_dcr_e1_wmean.hs
supreme_dc2_dr6d_v3_u_dcr_e2_wmean.hs
supreme_dc2_dr6d_v3_u_exptime_sum.hs
supreme_dc2_dr6d_v3_u_nexp_sum.hs
supreme_dc2_dr6d_v3_u_psf_e1_wmean.hs
supreme_dc2_dr6d_v3_u_psf_e2_wmean.hs
supreme_dc2_dr6d_v3_u_psf_size_wmean.hs
```

**Comment by erykoff** [comment]
Okay, all the files are now in `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/supreme/dr6-wfd` and this ticket can be closed.  Thanks!
