### ISSUE TITLE
[NERSC] Get more hours?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/desc-help#40]
I ran out of my desc (time) allocation and I was wondering if I could get a spare 10k or 20k hours.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [x] New User Account or account access problems(?)

**Comment by heather999** [comment]
Hi @fjaviersanchez While I cannot grant hours myself, there is a procedure to request more.  See this Confluence page for a link to a google form you can submit: https://confluence.slac.stanford.edu/display/LSSTDESC/How+To+Apply+For+NERSC+Computing+Time
and connect your request to an [approved DESC Project](https://confluence.slac.stanford.edu/display/LSSTDESC/LSST+DESC+Projects)

**Comment by fjaviersanchez** [comment]
Thanks a lot!! Closing this :)
