### ISSUE TITLE
Compiling packages with stack v19 on cori

### ISSUE THREAD

**Issue by rearmstr** [LSSTDESC/desc-help#41]
**Description**

I want to be able to use my own version of a package with v19 version the stack. The problem I am seeing is that packages with C++ code do not compile. I have tried a couple of different packages and they all have problems.  Maybe I am doing something wrong.  

Here is the output from trying to compile meas_algorithms:

/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v19.0.0/stack/miniconda3-4.7.10-4d7b902/Linux64/pex_exceptions/19.0.0/include/lsst/pex/exceptions/Runtime.h:46: undefined reference to `lsst::pex::exceptions::Exception::Exception(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: tests/test_imagePsf.o: in function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v19.0.0/stack/miniconda3-4.7.10-4d7b902/Linux64/boost/1.69.lsst1/include/boost/test/tree/test_unit.hpp:267: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: tests/test_imagePsf.o:(.rodata._ZTV15TestGaussianPsf[_ZTV15TestGaussianPsf]+0x28): undefined reference to `lsst::afw::table::io::Persistable::getPersistenceName[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: tests/test_imagePsf.o:(.rodata._ZTV15TestGaussianPsf[_ZTV15TestGaussianPsf]+0x30): undefined reference to `lsst::afw::table::io::Persistable::getPythonModule[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: tests/test_imagePsf.o:(.rodata._ZTV15TestGaussianPsf[_ZTV15TestGaussianPsf]+0x48): undefined reference to `lsst::afw::typehandling::Storable::toString[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::daf::base::PropertySet::getAsInt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `std::shared_ptr<lsst::afw::image::Image<double> > lsst::afw::math::offsetImage<lsst::afw::image::Image<double> >(lsst::afw::image::Image<double> const&, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `ROOT::Minuit2::MnUserParameters::Fix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::math::makeWarpingKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::FieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::getValue(char const*, boost::intrusive_ptr<ndarray::Manager> const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::daf::base::PropertySet::getAsDouble(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `ROOT::Minuit2::MnUserParameters::Add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::SubSchema::SubSchema(std::shared_ptr<lsst::afw::table::detail::SchemaImpl>, std::shared_ptr<lsst::afw::table::AliasMap>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::SchemaItem<int> lsst::afw::table::detail::SchemaImpl::find<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::pex::exceptions::Exception::addMessage(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::math::DoubleGaussianFunction2<double>::getPersistenceName[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::PointKey<double>::addFields(lsst::afw::table::Schema&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::SchemaItem<double> lsst::afw::table::detail::SchemaImpl::find<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::FieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::setValue(char*, boost::intrusive_ptr<ndarray::Manager> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::FieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::FieldBase(int)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::log::Log::getLogger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::Key<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > lsst::afw::table::Schema::addField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(lsst::afw::table::Field<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::detection::FootprintSet::FootprintSet<float, int>(lsst::afw::image::MaskedImage<float, int, float> const&, lsst::afw::detection::Threshold const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::AliasMap::apply(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::image::Mask<int>::getPlaneBitMask(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::BoxKey<lsst::geom::Box2D>::addFields(lsst::afw::table::Schema&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::math::Chebyshev1Function2<double>::getPersistenceName[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `std::shared_ptr<lsst::afw::image::MaskedImage<float, int, float> > lsst::afw::math::offsetImage<lsst::afw::image::MaskedImage<float, int, float> >(lsst::afw::image::MaskedImage<float, int, float> const&, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::io::PersistableFactory::PersistableFactory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::table::PointKey<int>::addFields(lsst::afw::table::Schema&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: lib/libmeas_algorithms.so: undefined reference to `lsst::afw::math::WarpingControl::setMaskWarpingKernelName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
scons: *** [tests/test_imagePsf] Error 1
scons: building terminated because of errors.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
 source /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v19.0.0/loadLSST.bash
 setup lsst_distrib
 git clone https://github.com/lsst/meas_algorithms
 cd meas_algorithms/
 git checkout 19.0.0
 scons

**Screenshots**

**Comment by johannct** [comment]
Hmm, so from the label I gather that you tried that at NERSC. So fwiw reproducing exactly your steps above results in a complete build at CC. I attaching the screen output in case it is useful.... The linker seems completely lost at NERSC....
[log_bob.txt](https://github.com/LSSTDESC/desc-help/files/5260124/log_bob.txt)

**Comment by heather999** [comment]
Some things to remember about the DMstack - with v19, we are depending on using an appropriate local compiler and older version of the C++ ABI,  while with more recent weeklies, DM has moved to use the conda-forge compilers which effectively is installed along with the code on CVMFS.  This means the situation gets easier with more recent versions of DMstack and the issue of local compilers and default ABI settings becomes hopefully irrelevant..  
For v19, all CVMFS installs include a README.txt, so you can see how it was built:
```
more /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v19.0.0/README.txt 
LSST Software
-------------

Product(s):          lsst_distrib
Tag:                 v19_0_0
Build time:          2019-12-06 11:24:23 UTC
Build platform:      CentOS Linux release 7.6.1810 (Core) Linux 3.10.0-957.1.3.e
l7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64
Python interpreter:  Python 3.7.2
C++ compiler:        c++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Conda:               conda 4.7.10
Documentation:       https://sw.lsst.eu
```
So we might stick with a compiler close to 8.3.1 (devtoolset-8) and make sure to load the appropriate environment at NERSC before compiling.  The other sticking point is the C++ ABI. For this version of DM built with devtoolset-8, it would be using the old ABI.  To accomplish what you want to do - we have to tell the compiler to use the old ABI.  Adding a flag like `-D_GLIBCXX_USE_CXX11_ABI=0 ` would be needed.  We had some [discussion about this on Slack](https://lsstc.slack.com/archives/C2U2K05JR/p1574362685125800?thread_ts=1573857670.075500&cid=C2U2K05JR) with Fabio and Michael.  [And also here with KT](https://lsstc.slack.com/archives/CLQL42BK9/p1570560664096500), where it remains foggy how we tell scons to set this flag.  I've sent a fresh inquiry and perhaps we can figure out how to do this.

The other option is to build against the v19 shifter image at NERSC and use that - same code, it's just that the environment will have devtoolset-8 available, so you can build successfully.  For vanilla v19.0.0 distributed by SQRE: `lsstsqre/centos:7-stack-lsst_distrib-v19_0_0` is already available at NERSC. Alternatively we have a v19 production version built using SQRE's image that includes the obs_lsst for DC2/Run2.2, extra stuff for metacal, generating object catalogs, etc:  `lsstdesc/desc-dr
p-stack:v19-dc2-run2.2-v5`
Here's an example build of meas_algorithms, which is [mentioned on Confluence](https://confluence.slac.stanford.edu/display/LSSTDESC/NERSC+Software+Installations#NERSCSoftwareInstallations-BuildingagainstShifterimages).  I just made sure to checkout v19.0.0.rc1 meas_algorithms locally and then started up shifter at NERSC:
```
shifter --image lsstsqre/centos:7-stack-lsst_distrib-v19_0_0
sh-4.2$ source scl_source enable devtoolset-8 
sh-4.2$ source /opt/lsst/software/stack/loadLSST.bash
(lsst-scipipe-4d7b902) sh-4.2$ setup lsst_distrib
(lsst-scipipe-4d7b902) sh-4.2$ ls
meas_algorithms
(lsst-scipipe-4d7b902) sh-4.2$ cd meas_algorithms/
(lsst-scipipe-4d7b902) sh-4.2$ setup -r . -j
(lsst-scipipe-4d7b902) sh-4.2$ scons
scons: Reading SConscript files ...
EUPS integration: enabled
Checking who built the CC compiler...gcc=8.3.1
CC is gcc version 8.3.1
Checking for C++14 support
Checking whether the C++ compiler works... yes
C++14 supported with '-std=c++14'
Setting up environment to build package 'meas_algorithms'.
Warning: test_ingestIndexReferenceCatalog.py should be run independently but can be automatically discovered
Running pytest with 1 process
pytest: automated test discovery mode enabled.
scons: done reading SConscript files.
scons: Building targets ...
```

Then you can run jobs either interactively or as batch, you just have to use the same shifter image and make sure to set up your local build of `meas_algorithms`

**Comment by rearmstr** [comment]
@johannct I tried a few weeks ago to do something similar at CC and I didn't have any problems. I haven't seen the error you report before.

@heather999 I was able to use the shifter approach to compile packages. Thank you!

**Comment by heather999** [comment]
Haven't heard anything from KT - for now I'm going to assume using shifter will work and as we move to more recent versions of the DMstack, this will no longer be a problem.
