### ISSUE TITLE
[NERSC] CCL not working

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#43]
**Description**
I am unable to load CCL.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [x] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
Run
1. source /global/common/software/lsst/common/miniconda/setup_current_python.sh
2. python
3. import pyccl

This is what I get:
```
awan@cori04:~: source /global/common/software/lsst/common/miniconda/setup_current_python.sh
Including user python path: /global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/
Now using /global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/bin/python
(desc) awan@cori04:~: python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyccl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/lib/python3.7/site-packages/pyccl/__init__.py", line 16, in <module>
    from . import core, constants, background, power, halomodel, pk2d, haloprofile, halos, massfunction, nl_pt
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/lib/python3.7/site-packages/pyccl/core.py", line 12, in <module>
    from .boltzmann import get_class_pk_lin, get_camb_pk_lin, get_isitgr_pk_lin
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/lib/python3.7/site-packages/pyccl/boltzmann.py", line 10, in <module>
    import camb
  File "/global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/camb/__init__.py", line 12, in <module>
    from . import baseconfig
  File "/global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/camb/baseconfig.py", line 51, in <module>
    camblib = ctypes.LibraryLoader(IfortGfortranLoader).LoadLibrary(CAMBL)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libifport.so.5: cannot open shared object file: No such file or directory
```

I see the same problem on an interactive node. I tried testing on JupyterLab but its currently taking forever to load.

**Comment by heather999** [comment]
HI @humnaawan 
I just tried this at NERSC with a fresh Cori login:
```
heatherk@cori03:~> bash
heatherk@cori03:~>  source /global/common/software/lsst/common/miniconda/setup_current_python.sh
Now using /global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/envs/desc/bin/python
(desc) heatherk@cori03:~> python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyccl
>>> 
```
Your output though does give us some clues, as it looking for packages like `camb` in your local $HOME, which is in the log you posted above:
`Including user python path: /global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/`
That happens if you have an environment variable called `$DESCPYTHONPATH` set and in this case it is pointing to your $HOME area. So in this case, when loading pyccl, it tries to load your local install of `camb` which seems to be incompatible. The first thing I would do is unset that DESCPYTHONPATH environment variable - you might have to check in your $HOME/.bashrc to see if it is set up there.  Now, then the question is, are there other packages you have installed under you $HOME that you need access to?

**Comment by humnaawan** [comment]
thank you @heather999! okay, so recently I changed the DESCPYTHONPATH entry in my bash profile since I wanted to have a local package work with the stack. Specifically, I had
`export DESCPYTHONPATH=/global/homes/a/awan/.local/lib/python3.7/site-packages`
and I changed it to
`export DESCPYTHONPATH=/global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/`

I just reverted back to the original path and I am now able to load `CCL` without a problem - thanks so much!

I am still unable to get my local package though (even with the second path I tried).

**Comment by heather999** [comment]
Hi @humnaawan 
There's a subtle difference between those two DESCPYTHONPATH path setting you tried and that second one includes `cori` in the path.  That means the packages you installed in this area: `/global/homes/a/awan/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/ ` were installed using one of NERSC's provided Anaconda installations - [see: here](https://docs.nersc.gov/development/languages/python/nersc-python/#installing-libraries-via-pip).  That definitely will not be compatible with `desc-python` which probably explains the error before.
I'm not sure why you see a difference at the command line versus jupyterLab yet..As long as DESCPYTHONPATH is set in your .bashrc, I would expect JupyterLab env to see it..   but maybe we can try this:  
An alternative would be to load `desc-python` at the Cori command line and install any additional packages with the desc-python environment setup - that would cause those packages to be installed under something like: `/global/homes/a/awan/.local/lib/python3.7/site-packages` and then hopefully those packages will work when you load desc-python.
Another alternative is to completely set up your own conda environment, based on desc-python and add whatever packages you want.  I started to document that here: https://github.com/LSSTDESC/desc-python/wiki/Add-Your-Own-Packages-to-the-desc-python-Environment  The hitch is that you need access to an area where you have space to clone desc-python, we have a quiet area here: `/global/common/software/lsst/users` where you should be able to create a new directory with your username, and then underneath that - you could clone desc-python and play with installing additional packages.  It's a little easier to manage, and remove installations that way without updating your $HOME/.local area.

**Comment by humnaawan** [comment]
thanks so much, @heather999 ! i'll try these solutions out. i'll close this issue though since my main issue is resolved - thanks so much!
