### ISSUE TITLE
ap_association installation on NERSC [NERSC]

### ISSUE THREAD

**Issue by reneehlozek** [LSSTDESC/desc-help#44]
**Description**
I'm trying to install ap_association on nersc. I've successfully installed ap_pipe, but the tests are failing for ap_association. I'm attaching the log file in case that is useful.

[ap_association.log](https://github.com/LSSTDESC/desc-help/files/5417621/ap_association.log)

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. Go to '/global/cscratch1/sd/rhlozek/alerts/ap_association'
2. Type  'scons'
3. See attache log file

**Comment by johannct** [comment]
I take that one, @heather999 ap stuff was on my list anyway for the alert broker current efforts within the topical team

**Comment by heather999** [comment]
See Slack: https://lsstc.slack.com/archives/C2U2K05JR/p1603300088036500?thread_ts=1603299941.036400&cid=C2U2K05JR

**Comment by johannct** [comment]
closing as discussed on slack : for now work with the ap packages available in the lsst_distrib weeklies
