### ISSUE TITLE
Can we have default group = lsst instead of user name ?

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#46]
**Description**
A clear and concise description of what the issue is.  
For newly created files, default group is usually the username, making it difficult to share
files because permission have to be manually changed. Would be much easier if we all have default group=lsst.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [x] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi @RickKessler 
On the NERSC Community File System (CFS), such as under `/global/cfs/cdirs/lsst/groups/SN`, the default is set such that all files and directories have `lsst` UNIX group access.  Now elsewhere on the NERSC filesystems such as your $HOME or on $CSCRATCH, the NERSC default follows what most unix systems provide, which is a default where all files and directories you create are set to your username as the group.
You can change this for your $CSCRATCH or $HOME or choose to set up a specific directory under those filesystems dedicated to DESC  - that's particularly useful for those of us on multiple repositories at NERSC and may not want to share everything with DESC. I agree, making that automatic is much better to support sharing of files and directories without having to reset permissions all the time.
Under either $CSCRATCH or $HOME or both you can do:
```
setfacl -m g:lsst:x $HOME
mkdir $HOME/desc
chgrp lsst $HOME/desc
chmod g+s $HOME/desc
```
Now anything you create under $HOME/desc should be read accessible by anyone in the lsst UNIX group, you can do the same on $CSCRATCH.

**Comment by RickKessler** [comment]
FYI: I tried this and it seems to work !
