### ISSUE TITLE
potential issue with gcc version 8

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#48]
**Description**
A clear and concise description of what the issue is.  
Using the Cori DESC-SN environment, I found evidence that all of the gcc/8.xxx versions (including default 8.3.0) may have an issue. gcc/7.xxx and gcc/v9.xxx work fine. Can we move default gcc to v9 ?

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

Here are more details about the gcc issue.
I recently noticed one of the snana programs giving very strange behavior ($SNANA_DIR/src/combine_fitres.c). It runs to completion, but output is clearly incorrect. I thought it was a bug, but found that it works fine when removing the -O1 optimizer flag. Next I restored the -O1 flag and tried different gcc versions. All of the gcc/v8.xxx give the same failure; gcc/7.3.0 and both of the gcc/v9 versions work fine. Can we change default gcc to v9 ?

**Comment by heather999** [comment]
Looking ahead to the Nov NERSC maintenance, they will be [removing gcc/9.2.0](https://docs.nersc.gov/systems/cori/timeline/default_PE_history/2020Nov/), so we should plan to move to gcc/9.3.0.
For snana, the only question is making sure the ROOT module you're using is compatible and I think it is.  So to do this, I think we'd update: `/global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh`
and `/global/cfs/cdirs/lsst/groups/SN/snana/SNANA_setup.sourceme` to use gcc/9.3.0
Then there needs to be a snana rebuild. I can help out with updating the setup_sn_all.sh and even the SNANA_setup.sourceme scripts.  After that do you want to handle the snana rebuild?  Am I forgetting something?

**Comment by RickKessler** [comment]
just let me know when the global setup changes gcc version and I will update SNANA setup and re-run make. Note that /global/cfs/cdirs/lsst/groups/SN/snana/SNANA_setup.sourceme is essentially obsolete, but might be useful later for specialized development.

**Comment by heather999** [comment]
Hi @RickKessler I just updated `/global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh` to use gcc/9.3.0  ( I also saved a back up of the original setup_sn_all.sh as setup_sn_all-gcc8-old.sh just in case).  Please rebuild snana and we'll see how it goes!

**Comment by RickKessler** [comment]
re-made SNANA with gcc v9.3, and re-ran the test suite of ~100 jobs ... looks good.
