### ISSUE TITLE
[NERSC] Move dr6_wfd matched catalog to CFS

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/desc-help#49]
**Description**
Hi all! This issue is similar to #32. Would it be possible to copy the matched catalogs at `/global/cscratch1/sd/jsanch87/dr6_wfd_matched` to a more permanent location, please?

Thanks in advance! 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Ok - done!

**Comment by fjaviersanchez** [comment]
So fast!! Thanks a lot! :)
