### ISSUE TITLE
[NERSC] Remove old desc-dia jupyter kernel

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#50]
**Description**
The desc-dia env was set up during a collaboration meeting to help out with Sprint/Hacking.  It is completely out of date and should either be updated or removed.  I'd like to consult with the SN group to see if we should just remove this, replace it with a desc-sn, or if desc-stack environments are suitable.  As it stands the `desc-dia` environment confuses people, because they think it is up to date. 
Calling @BrunoSanchez @RickKessler @kponder  @wmwv 

Choose all applicable topics by placing an 'X' between the [ ]:
- [X] jupyter
- [X] Cori interactive command line
- [ ] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by BrunoSanchez** [comment]
I have fell for this in the past. Almost everything there is outdated. 
Feel free to proceed for what concerns me.
