### ISSUE TITLE
can no longer log into Cori

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#52]
**Description**
Each attempt to log into Cori results in the following:

Login connection to host cori06 :
Password + OTP: 
Password + OTP: 
Password + OTP: 

There is no error message; it just keeps asking me to re-enter pw + OTP.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [x] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
There seems to have been an issue with OTP when used to log into Cori which seems to have resolved itself.  
Others report on [Slack](https://lsstc.slack.com/archives/C2U2K05JR/p1606837072134300) that they can now use OTP to log in, and I can also confirm things work for getting onto iris and jupyter.nersc.gov.

**Comment by RickKessler** [comment]
yep, I can indeed log in now.
