### ISSUE TITLE
[NERSC] Add kmeans_radec to DESC python environment

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-help#53]
**Description**

A new DESCQA [test](https://github.com/LSSTDESC/descqa/pull/102) uses Erin Sheldon's [kmeans_radec](https://github.com/esheldon/kmeans_radec). Since now DESCQA execution [uses DESC python environment](https://github.com/LSSTDESC/descqa/pull/213), we will need to add this package to DESC python environment. 

This package can be installed py

```bash
pip install https://github.com/esheldon/kmeans_radec/archive/master.zip
```

It does not have any special dependencies (only `numpy`). 

Thanks, @heather999!  (cc @evevkovacs)

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
N/A

**Screenshots**
N/A

**Comment by heather999** [comment]
I can add it into desc-python and desc-python-bleed.  
I would like to ask that we try to provide at least tagged versions for installation.  How can we most easily encourage that? I can open a ticket on the repo and ask.  Maybe for now, I'll first add this to desc-python-bleed and if we can get a tag, I will add it to desc-python.
We might also want to encourage "new" packages to support conda-forge installation early on, so it's one less package we have to deal with later, but that's not a show-stopper for right now.

**Comment by evevkovacs** [comment]
Chun Hao To has submitted a PR to remove this dependency from the code and use a module from Treecorr, which may solve the issue. We will test it and get back to you.

**Comment by evevkovacs** [comment]
Chun Hao comments that:  However, I notice that /global/common/software/lsst/common/miniconda/current/envs/desc/bin/python doesn't have kcorrect_python installed, which is needed for the module and can be installed by pip. So, we may need kcorrect_python  instead.

**Comment by heather999** [comment]
This package is kcorrect_python?  https://github.com/nirinA/kcorrect_python
It doesn't seem to be a very active repo.  I'll start by adding it to desc-python-bleed and you guys can tell me if it works as expected.
Just linking the descqa issue here for reference: https://github.com/LSSTDESC/descqa/pull/102

**Comment by heather999** [comment]
It appears `kcorrect_python` is not pip installable, at least not using the desc-python env.  The README recommends a manual installation - I can give that a try.  I'm a little concerned about the long term support for this particular package.
```
pip install https://github.com/nirinA/kcorrect_python/archive/v2017.07.05.tar.gz
Collecting https://github.com/nirinA/kcorrect_python/archive/v2017.07.05.tar.gz
  Downloading https://github.com/nirinA/kcorrect_python/archive/v2017.07.05.tar.gz
     \ 114 kB 1.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/py3.7/envs/desc/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3_rlpvm7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3_rlpvm7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kunzg1b_
         cwd: /tmp/pip-req-build-3_rlpvm7/
    Complete output (1 lines):
    KCORRECT_DIR must be set
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by johannct** [comment]
We really need to put something in place for evaluation and acceptance of new packages.....

**Comment by johannct** [comment]
So the first thing is : no manual installs, and the second at this stage is indeed, conda-forge installation. If an external package is needed but is not up to these standards or seem stale, it is always possible to fork it and take proper responsibility for the forked project.

**Comment by heather999** [comment]
I agree.. For `desc-python-bleed` we can be more flexible to allow for evaluation of a package.  `desc-python` has a much higher threshold and this `kcorrect` package does not come close to meeting it.

**Comment by johannct** [comment]
> I agree.. For `desc-python-bleed` we can be more flexible to allow for evaluation of a package. `desc-python` has a much higher threshold and this `kcorrect` package does not come close to meeting it.

Even for desc-python-bleed we need to put something in place, so that people know that it evaluates properly with respect to the expected infrastructure once bumped up into desc-python

**Comment by evevkovacs** [comment]
I left a comment on the original issue https://github.com/LSSTDESC/descqa/pull/102. Should we go back to using to Erin Sheldon's version https://github.com/esheldon/kmeans_radec ?  (Sorry for taking us in circles here)

**Comment by johannct** [comment]
> I left a comment on the original issue [LSSTDESC/descqa#102](https://github.com/LSSTDESC/descqa/pull/102). Should we go back to using to Erin Sheldon's version https://github.com/esheldon/kmeans_radec ? (Sorry for taking us in circles here)

The order of the discussion above was : kmeans_radec dependency, then PR to remove it and use a Treecorr module, then realization that there is still an unmet dependency over kcorrect_python. 

So what does going back to kmeans_radec solve? Erin is a DESC collaborator, there is 0 issue with integrating any necessary repo from him, and we can work out with him how to package it in a proper way for inclusion. The issue right now is a stale third party package named kcorrect_python.... What is it that depends on it?

**Comment by evevkovacs** [comment]
Sorry I misunderstood the nature of the problem. I thought that the kcorrect_python dependency was as a result of migrating to the Treecorr version.

**Comment by johannct** [comment]
Treecorr is in the tool stack as far as I know...... so it should not have any issue with a kcorrect_python package. We will need some time with Heather to brainstorm further and put in place a framework for anyone to be able to test integration of one's code into the DESC framework. Stay tuned.

**Comment by johannct** [comment]
in the meantime, please track back where kcorrect_python dependency come from.

**Comment by yymao** [comment]
Sorry for not being able participate in this thread yesterday. Here's where we are:

- The dependency of `kmeans_radec` from [descqa#102](https://github.com/LSSTDESC/descqa/pull/102) has been removed. 
- The dependency of `kcorrect` from [descqa#102](https://github.com/LSSTDESC/descqa/pull/102) is in fact optional, and we are exploring options that do not require installing `kcorrect` into DESC environment (see [my comment here](https://github.com/LSSTDESC/descqa/pull/102#issuecomment-743770676)). 

As such, no action from desc-help is needed at this moment, and I'm closing this issue. Thank you all for your comments and help.
