### ISSUE TITLE
[NERSC] Copy files from cscratch to shared directories for DC2 run2.2i V2 photo-z reader

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/desc-help#55]
I have computed photo-z catalogs for the dc2_object_run2.2i_dr6_v2 catalog. The files are 166 parquet files with name pattern:
photoz_pdf_Run2.2i_dr6_tract_*.parquet 
 in my cscratch directory at:
/global/cscratch1/sd/schmidt9/Run2.2i_V2/outputs/

Can you please copy these files to the shared space, namely a new directory named:
/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/photoz/dr6_v2/

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Copied 166 files to: ` /global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/photoz/dr6_v2/`  Just let me know if you see any problems!

**Comment by sschmidt23** [comment]
Files copied and seem to work, closing.  Thanks!
