### ISSUE TITLE
PLASTICC sim jobs run super slow in batch queue

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#58]
**Description**
A clear and concise description of what the issue is.  

SNANA simulations for PLASTICC run about x10 slower in Cori batch system compared to running interactively, or running on our U.Chicago batch system. The problem seems intermittent, and there are no error messages in the logs. Not sure if this issue is related to particular batch nodes, resources, or disk I/O. Advice on further diagnostics would be appreciated.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
HI @RickKessler Can you give some details about how these jobs are run?  Is this Cori Haswell or KNL? How many nodes, amount of memory use?  Is the I/O on CSCRATCH? Is this using ROOT?
Slurm offers some tools to look at data associated with recent jobs: https://docs.nersc.gov/jobs/monitoring/#sacct
It might be helpful to define some general test job you can run on both systems so we can try to do some comparisons.

**Comment by RickKessler** [comment]
cd /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC/survey_config/SIMLOGS_LSST_DDF_REF
more CPU0000_JOBLIST_cori10.BATCH

**Comment by heather999** [comment]
Hi @RickKessler I see the directory and the general parameters used to submit jobs.  To move forward, it would be best to create a small test case that we can run interactively, at Chicago, and on Cori batch - so we can make some comparisons.  With some numbers in hand, we can approach NERSC for advice.  Can you help devise such a test case that we can run?

**Comment by RickKessler** [comment]
here is a speed-test summary for generating 100 Mdwarf events:
   /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/kessler/speed_test
On U.Chicago Midway2 cluster, the CPU times are the same running interactively and in batch. On Cori, however, the batch CPU is almost x10 greater compared to interactive.

**Comment by heather999** [comment]
Hi @RickKessler ,
Finally got back to this. I see your results
```
more AAA_CPU_SUMMARY.TXT

CPU to generate 100 Mdwarf events:
   Cluster        Interactive       Batch
# ------------------------------------------
  NERSC-Cori        0.3 min        2.0 min
  UofC-Midway2      0.5 min        0.5 min
# ------------------------------------------

[CPU measured by C code, and thus does NOT include
 overhead from waiting in batch queue]
```
I ran RUNTEST_INTERACTIVE on a vanilla Cori login node, and that ran about 20 seconds for me:
```
User time (seconds): 18.28
System time (seconds): 1.46
Percent of CPU this job got: 96%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:20.55
```
Then I repeated that same simple test, but made my own batch script utilizing what you had in /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC/survey_config/SIMLOGS_LSST_DDF_REF as an example:
```
#!/bin/bash
# ??? 1',   '1' ???

#SBATCH -J SIMGEN_MASTER_LSST_DDF.INPUT-CPU0000
#SBATCH -q shared
#SBATCH -A m1727
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 24:00:00
#SBATCH -L SCRATCH,cfs
#SBATCH -C haswell
#SBATCH --output=HMK_CPU0000_JOBLIST_cori10.LOG
#SBATCH --mem-per-cpu=8GB

echo $SLURM_JOB_ID starting execution `date` on `hostname`

/usr/bin/time --verbose snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT \
   INPUT_FILE_INCLUDE: $PLASTICC_ROOT/model_config/SIMGEN_INCLUDE_LCLIB_Mdwarf-LSST.INPUT \
   GENTYPE: 65 \
   NGENTOT_LC: 100 \
   SEARCHEFF_SPEC_SCALE: 1.0 \
   SIMLIB_FILE: $SNANA_LSST_ROOT/simlibs/PLASTICC_ORIGINAL_DDF.SIMLIB \
   SOLID_ANGLE: 0.01451 \
   SEARCHEFF_zHOST_FILE: $SNANA_LSST_ROOT/models/searcheff/PLASTICC_ORIGINAL_zHOST_4MOST_DDF.DAT \
   > HMK_OUT_BATCH_Cori.LOG
```
Two things changed: I added "cfs" to the #SBATCH -L line and removed "project", and the SIMGEN_TEMPLATE_LSST.INPUT is now on SCRATCH.  I submitted to batch and it ran in real-time about 1 min 30 seconds, but didn't have as much exclusive access to the CPU, so we note that the user time is ~24 seconds:
```
	User time (seconds): 23.53
	System time (seconds): 8.77
	Percent of CPU this job got: 33%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:35.77
```
 repeated the test using the "debug" queue:
```
User time (seconds): 17.16
System time (seconds): 3.62
Percent of CPU this job got: 29%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:10.17
```
so.. yes the real-time is longer than running interactively, but the user time is about the same - so it seems to me to be a question of CPU utilization. It would be interesting to try a longer test. I haven't tried your `RUNTIME_BATCH` script, for fear of overwriting your data, as I haven't taken the time to try to see how the output is set up.

**Comment by RickKessler** [comment]
feel free to launch RUNTIME_BATCH, as there is nothing important here to save. Let me know how big of a job you'd like to try next and I can update the job parameters accordingly.

**Comment by heather999** [comment]
HI @RickKessler I'd like to run snlc_sim.exe for 15-30 minutes and maybe something longer like 1-2 hours.
How do you do your timing estimates?

**Comment by RickKessler** [comment]
grep NGENTOT SIMG*
SIMGEN_MASTER_LSST_DDF.INPUT:      NGENTOT_LC: 100
SIMGEN_TEMPLATE_LSST.INPUT:NGENTOT_LC: 100

increase the NGENTOT args as you like, then execute the RUNTEST_BATCH and RUNTEST_INTERACTIVE scripts. E.g., replacing 100 with 1000 should run x10 longer.

**Comment by RickKessler** [comment]
I recently noticed that while the sims run quite slow in batch mode, the light curve (LC) fits run at normal speed. This motivated the following sim tests that identified the source of the problem:

* write sim output to /global/cfs/cdirs/lsst/groups/SN/snana instead of scratch:
   --> no change
* read SIMLIB/cadence every 10 events instead of every event
   (re-use each cadence 10 times before reading next cadence)
   --> x3 faster

So the issue seems to be reading the SIMLIB/cadence text file each event. Note that LC fitting reads FITS data for each event, but doesn't seem to suffer. For the	DC2-sim	test that I ran, the average cadence has ~300 rows to read, which is an order-of-magnitude more than the number of data rows read by LC fit program. For the PLASTICC sims, the number of rows per cadence is 500-600.

**Comment by RickKessler** [comment]
I revived this issue because of new information about slow performance in batch mode on Cori. For writing Avro alerts there is a task to tar large groups of files. We noticed that the tar task is more than x10 slower in batch compared to interactive. This will add 10-20 hours of wall-time when we process the full PLASTICC sample, and may be a clue to the slow performance of generating sims.

**Comment by heather999** [comment]
That is a good clue.  I wonder if the task to tar could be sent to one of [NERSC's Data Transfer Nodes](https://docs.nersc.gov/systems/dtn/) and then the rest of writing Avro alert tasks could be handled by typical batch nodes?  Does the tarball task precede some step to move the data?

**Comment by RickKessler** [comment]
The tarball task of part of a generic "post-process/merge" step in the submit_batch framework, and it runs as part of the batch job. If this is a clue to slow simulations, then using data transfer nodes isn't the complete solution. My hunch is a file I/O issue in batch mode.

**Comment by heather999** [comment]
I think we will need to demonstrate the performance difference when running in batch vs on a login node to NERSC and open a ticket.  Is there a relatively easy way to do that?  Could it be as simple as running a large enough tar task on both a login node and on a batch node?

**Comment by RickKessler** [comment]
I setup a test here on Cori:
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/kessler/makeAlert_tarball_test

./RUNMERGE_INTERACTIVE
./RUNMERGE_BATCH

produces  MERGE.LOG_INTERACTIVE and MERGE.LOG_BATCH, which shows NDIR/sec in the last column of the COMPRESS table. NDIR/sec is how many NITE directories per second are converted into tar balls. The interactive speed is 60-70; the batch speed is ~4. The timer is wrapped around the tar command and does NOT include the time to restore the original PLASTICC_ALERTS_SHORT directory.

Note that both of the RUNMERGE_XX commands operate on the same directory, so only one script can run at any given time.
