### ISSUE TITLE
NERSC Onboarding Planning

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#59]
As discussed at today's DM/DA meeting, we would like to put together a NERSC Onboarding session modeled after the [DESC Onboarding Session from March 3rd](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+Seminars).  See the [slide deck](https://docs.google.com/presentation/d/1WVwMiRS-Xh-6Jx9bzUX6lLBiqRlCEPORnNxFk138pLU/edit?usp=sharing) for inspiration.
This is meant to potentially be a recurring session to help new members or newly re-engaged members to get started using NERSC resources.
The session would be organized with one stop per topic, led by a variety of "friendly guides".  
Looking for topic suggestions, how to best handle the session as a whole (do we demo?  are we just providing an overview of resources available to learn more?) and volunteers to help lead "stops". 

Our list of stops and who will present them are also mentioned in a [later comment](https://github.com/LSSTDESC/desc-help/issues/59#issuecomment-825256120):
* NERSC's mission
* Overview of NERSC systems (Cori Haswell & KNL) 
* Managing a NERSC account (including log-in node, module, NX, screen, etc) & Filesystems 
* How to find DESC data 
* Software available (including DESC software installations)
* JupyterHub 
* Running jobs (including interactive queue, a note about login nodes vs compute nodes, debug queue, etc.) 
* Resources (where to get help, monitoring tools, NERSC outages, NERSC ticketing system, etc) 
* Transition to Perlmutter

**Comment by JoanneBogart** [comment]
Maybe filesystems and finding DESC data should be separate topics.  GCR and Butler support finding datasets by name, and the accessible filesystems are irrelevant for database access.

**Comment by heather999** [comment]
Mostly agree!  I think it's useful to explain the `/global/cfs/cdirs/lsst/shared` area as well as data access methods which may not particularly care where things reside.

**Comment by JoanneBogart** [comment]
Certainly the shared area should be explained, but I think within the context of the other filesystems.  The emphasis for data access is different.

**Comment by heather999** [comment]
We are on the calendar for Wednesday 8 AM June 30th!

**Comment by heather999** [comment]
Time to start gathering people willing to take on specific topics for this Onboarding session.  Please add your name next to one of the topics below and we can start checking these off.

- [ ] Managing a NERSC account
- [ ] Overview of NERSC systems: Cori Haswell & KNL
- [ ] Filesystems 
- [ ] How to find DESC data
- [ ] Software available - including DESC software installations
- [ ] JupyterHub (demo?)
- [ ] Running jobs - including interactive queue, a note about login nodes vs compute nodes, debug queue, etc (demo?)
- [ ] Resources: where to get help, monitoring tools, NERSC outages, NERSC ticketing system..
- [ ] Transition to Perlmutter

**Comment by heather999** [comment]
Starting to set up the [skeleton slide deck](https://docs.google.com/presentation/d/1aNJoWls870Oq7HQKpjy72F8fcQmEDoNruIVLHjqnUiI/edit?usp=sharing), please feel free to start adding in content for your slide!

Also collecting ideas to improve our Confluence documentation - so if you have ideas for your topic, please feel free to insert a request or update Confluence as you see fit :)

- [ ]  Pull out NERSC account management from the "[Getting a NERSC Account](https://confluence.slac.stanford.edu/display/LSSTDESC/Getting+a+NERSC+Computing+Account)" page.

**Comment by heather999** [comment]
@JoanneBogart @heather999 @yymao @TomGlanzman @jchiang87 @joezuntz @djbard It's June!  I'd like to ask that we try to write up a draft of our slides by Wednesday, June 16th.  That will give us some time to go over the content and refine things.  I'll be cleaning up the example skeleton to make sure there is a proper example, but if you have any questions please feel free to post them here and we can start sorting out the details.  We're basing this heavily on the [DESC Onboarding session](https://docs.google.com/presentation/d/1WVwMiRS-Xh-6Jx9bzUX6lLBiqRlCEPORnNxFk138pLU/edit?usp=sharing) from last March, where we intend to have about 1 slide per topic and provide back up slides as needed.

**Comment by yymao** [comment]
@heather999 a quick question -- will you cover installing DESC kernels in "Software available" or should I cover it in my JupyterHub Demo?

**Comment by heather999** [comment]
HI @yymao I was thinking to include DESC kernels in the "software available" slide.  And a question for you!   Do you want to run any demo in jupyter?  Would we expect all participants that day to attempt connecting to jupyter during the session?  I'm thinking I probably should give NERSC a heads up, if so.

**Comment by joezuntz** [comment]
@heather999 I've added the slides on submitting jobs at NERSC. I think someone earlier is explaining the different node types so I skipped one slide.

**Comment by yymao** [comment]
@heather999 great, so I will leave kernel installation to you. 

I do plan to run a demo but am not planning to ask all participants to follow me step-by-step (since the time is short).

**Comment by yymao** [comment]
@heather999 Should we put down the time for each stop? I am thinking through what I want to cover but need to know how much time I have... it's easy to overrun :slightly_smiling_face:

**Comment by heather999** [comment]
Short answer, "Yes" :)  Longer answer - some stops definitely deserve more time:  Jupyter, Running Jobs, and Transition to Perlmutter.  I think these 3 stops should have 8-10 minutes each, and the remaining 5 stops would have 5 minutes each (where I expect some may not need that much time).  That will easily eat up our hour and hopefully still allow a few minutes for a couple of questions.
Other suggestions?

**Comment by yymao** [comment]
Thanks @heather999. 

3*8 + 5*5 = 49 sounds reasonable, as we still need some time for welcoming people, transition, and take questions. Maybe it's still a bit tight but ok. I guess we should all plan to not fully use up our time (and certainly not go over). 

If others are happy with this time distribution, I'll plan accordingly for my part.

**Comment by JoanneBogart** [comment]
5 minutes should be plenty for mine. I will try to make it 3 or 4.

**Comment by JoanneBogart** [comment]
In the skeleton slide deck there is an unassigned stop #3 "NERSC Filesystems".  Tom has already covered this (I think sufficiently) in his stop.  Can we get rid of the separate filesystems stop?

**Comment by heather999** [comment]
yes - actually I've only been updating the checklist here: https://github.com/LSSTDESC/desc-help/issues/59#issuecomment-825256120  Just fixed the initial comment to remove "NERSC Filesystems"

**Comment by JoanneBogart** [comment]
But the rest of that line (Overview of how to find DESC data) is still a stop.

**Comment by heather999** [comment]
Thanks to all for setting up your slides!  Katrin has kindly agreed to act as our "guide", she will be handling the initial introduction, deal with sharing the slides and introducing each of us when our stop is presented.  As was done for the DESC onboarding, we'd like to use this opportunity to introduce people to other DESC members, including a sense of what we do in DESC.  Can each of you add your "position(s)" in the slide notes under your first slide? Katrin can use that information when introducing each of us.

**Comment by heather999** [comment]
@joezuntz Thanks for putting together your slides!  Now for questions!  
11 slides seems ambitious to cover in 8-10 minutes.  I'm not expecting we want to encourage live demo or have people try these example commands in real-time. To keep with the general "Onboarding" model - we really want to keep it to a slide or two, with links to useful documentation that people can refer to later.  We have been hoping to create a "running jobs at NERSC" Confluence page which might be a good home for the details in these slides longer term.  I'm wondering if we can go ahead and do that now, and then update these Onboarding slides to summarize the content and point at Confluence (which will also point to NERSC doc)?

**Comment by joezuntz** [comment]
Hi Heather,
My intention was always to skip over most of the material and leave it as reference material.  I've made an explicit split now on the slides - does that look alright?  So I would basically just talk through the first few sentences and describe what the reference material is, but not go through it.

**Comment by heather999** [comment]
Hi Joe - that sounds reasonable.  Right now it looks like slide 12 is set to "skip" but 13 through 23 are available for viewing during the session.  Is the thought that the slides are accessible but the intent is that we won't go through them during the onboarding session and people should go back to them later?

**Comment by joezuntz** [comment]
Hi Heather - I planned to show them briefly, just to give people an idea of what's there, yes.  I'll go through them but just talk verbally about the upper part of the slide.  I'll delete 12 - I assume that stuff is covered by someone earlier?

**Comment by heather999** [comment]
Sorry I should has said 13 is set to "skip".  I think it's fair to assume that content will be covered by @TomGlanzman - at least the Cori bits and then Debbie will be talking about Perlmutter at the end.  If there's something you feel should be called out in their slides - maybe check in with them?

I think I'm going to plan to go ahead and capture a lot of the content you have kindly written in Confluence so it'll be a longer lasting resource.

**Comment by heather999** [comment]
Hi all - also looking to find a facilitator for our session - someone who will be available to share links as needed in the chat, just like the role during the DESC Onboarding session.  Looking for suggestions! I don't necessarily want to trouble someone who would otherwise want to be listening more closely..

**Comment by heather999** [comment]
@joezuntz @yymao @JoanneBogart @TomGlanzman @djbard @jchiang87 Tomorrow is the day!  Please take a moment and check your slide to see if there is anything you would like to have posted into the chat during your "stop".  This could be a link to a confluence page or some other useful site.  I went ahead and added "www.nersc.gov" to Debbie's Tour Stop 1, for example (Debbie - feel free to remove/change that!)

**Comment by heather999** [comment]
Last message from me.. Just as in the DESC Onboarding session, we're going to have each of us share screen for our own slide(s).  I'll be connected at 7:45 AM PT and available to help test our sharing, microphones, etc.

**Comment by JoanneBogart** [comment]
From experience with the DESC Onboarding session, is it considered helpful to people to follow links briefly so they can get a preview or is it more likely to be disorienting?

**Comment by jchiang87** [comment]
Someone else will have to share screen for my slides. (I don't intend to follow any links during my presentation.)  I always have a hard time unsharing screen from my laptop and don't want to struggle with that tomorrow.

**Comment by JoanneBogart** [comment]
I don't usually have any problems and can do it if need be.

**Comment by heather999** [comment]
@joezuntz Given that you present just before @jchiang87's stop - can you keep sharing your screen when you are finished and move onto the "Resources" Tour Stop 8?  Then when Jim is done, stop sharing, and @djbard can share her screen for the final stop?

**Comment by joezuntz** [comment]
Yep, sure.

**Comment by heather999** [comment]
@JoanneBogart To answer your question about following links - I'd say it depends :) When we get to your stop, @BrunoSanchez will post in Chat what is in the slide notes: 

> For a comprehensive list of what’s available, see https://confluence.slac.stanford.edu/x/oJgHDg

The participants will hopefully follow that link and then during your bit - you can jump from your slide to that Confluence page and talk through it there.  If you're more comfortable staying on your slide and just referring to the Confluence page, that should be fine too.

**Comment by JoanneBogart** [comment]
I wrote up notes for myself covering what I intended to say, not quite all of which I _did_ say. Would these be of use more generally?  If so, where do I put them?

**Comment by heather999** [comment]
I think that could be useful.  In fact I think writing up what I **wanted** to say (versus what I **did** say) for my 2 slides might be helpful too!  Two thoughts come to mind.. you could add this to the slide notes on [your slide](https://docs.google.com/presentation/d/1aNJoWls870Oq7HQKpjy72F8fcQmEDoNruIVLHjqnUiI/edit#slide=id.gbeb409bd31_0_18) or maybe insert this above the Q&A in the [live notes](https://docs.google.com/document/d/1hsQd4JDPgscUkGEw6m8qL_Fxy8JyRvMSBYHzDePXlMc/edit#heading=h.2o4wp6dcvuvh)..  It may depend on how long the notes are and where we think they are most likely to be seen.  I could imagine inserting notes in both places :)

**Comment by JoanneBogart** [comment]
Thanks, @heather999 !  I was thinking about the slide notes...I'll do that to start.  I think in their present form they'll be easier to understand there than "stand-alone" in the live notes.

**Comment by heather999** [comment]
NERSC Onboarding done
