### ISSUE TITLE
[NERSC] Copy new redmapper v0.7.5 catalogs from cosmodc2 to shared data.

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#60]
**Description**
A clear and concise description of what the issue is.  

I have a new version of the redMaPPer catalog from cosmodc2 v1.1.4 that fixes the issues from v0.5.7 (previously released).  Specifically, central galaxies are now properly in the member file, and there are no missing regions.

The files are currently here:
`/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.7.5_lgt20_catalog.fit`
`/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.7.5_lgt20_catalog_members.fit`

And should be copied to:
`/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmapper_v1.1.4/`

I will make a PR to `gcr-catalogs` to make these catalogs available when they are transferred.

Thanks!

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ x ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Sorry @erykoff can I get you to set the permissions so I can access those files?  Maybe allow reading by the `lsst` group.

**Comment by erykoff** [comment]
Argh, you're right.  I made the files readable but forgot about the directory.  Please check now!

**Comment by heather999** [comment]
Got them - the contents of shared area now looks like:
```
ls /global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmapper_v1.1.4/
cosmoDC2_v1.1.4_mag_run_redmapper_v0.7.5_lgt20_catalog.fit
cosmoDC2_v1.1.4_mag_run_redmapper_v0.7.5_lgt20_catalog_members.fit
cosmoDC2_v1.1.4_run_redmapper_v0.2.1py_lgt20_catalog.fit
cosmoDC2_v1.1.4_run_redmapper_v0.2.1py_lgt20_catalog_members.fit
cosmoDC2_v1.1.4_run_redmapper_v0.5.7_lgt20_catalog.fit
cosmoDC2_v1.1.4_run_redmapper_v0.5.7_lgt20_catalog_members.fit
```
