### ISSUE TITLE
need fast/debug queue to test code changes

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#63]
**Description**
A clear and concise description of what the issue is.  

I have recently starting training SN group members to make SNANA code changes on Cori, but a regression test needs to run before submitting a pull request. This "SNANA_code_test" script launches about 100 short jobs in batch, and takes a few CPU minutes per core with 10 cores. The problem is that it can take an hour or more just to get into the queue, making this final step very slow. I have tried using debug queue, without success ... probably mis-understood something form NERSC doc.

Here is the current/nominal batch template file used by SNANA:
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/SBATCH_TEMPLATES/SBATCH_DEFAULT.TEMPLATE

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [x ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by johannct** [comment]
reading the description cursorily, it seems that what you describe is a regression test that would normally belong to an automatic CI setup as the ones github provide through actions, and that we are advocating for desc. Wouldn't that be a possible path to follow, or is it critical that this runs at NERSC?

**Comment by RickKessler** [comment]
I have had CI discussions several times in the past, and it was never clear if CI will work with SNANA because of code compilation that includes C, fortran, and several libraries that may be difficult to setup. The input files consume about 400MB, but I would guess that this is not a limitation. The current SNANA-test script system is about 10 years old, and works on multiple clusters (FNAL, U.Chicago, NERSC). The strategy is to quickly find problems before submitting code to git. I am open to learning the CI method, but first want to check if it is really feasible.

**Comment by johannct** [comment]
Ok, github actions just list a sequence of commands in essance and can also execute a make command over a Makefile, so provided the core libraries are there, it should be close to a user experience building SNANA. I am willing to give it a try to get my hand dirty with SNANA for the first time, as a result. Incidentally we received an email from NERSC announcing a presentation to the users of their gitlab based CI solution..... so all the more a timely reflection to have. Thoughts @heather999 ?

**Comment by heather999** [comment]
Hi @RickKessler a few thoughts!
NERSC is actively looking at ways to provide CI tools that allow automated triggering of testing in response to code updates (which I imagine could include a Pull Request).  There is a session next week that I'm going to attend: https://www.nersc.gov/users/training/events/introduction-to-ci-at-nersc-july-7-2021/ and will have a better idea of how we could utilize CI for your testing needs.
In the meantime..
So right now you guys are manually submitting a script to run jobs and getting stuck in the queue?  To get an improvement quickly, I would try the ["interactive" queue](https://docs.nersc.gov/jobs/interactive/) rather than "debug" (time limited) or even "shared" due to the potential time stuck in the queue.  The interactive queue should start up within 6 minutes and you have access for up to 4 hours, but you are limited to only 2 jobs at a time. Is there a way to reconfigure those 100 shorts jobs?  Maybe you can show us how you guys start up those test jobs now and we can modify the template?

**Comment by RickKessler** [comment]
I tried interactive queue with 2 jobs using this batch template:
/global/cfs/cdirs/lsst/groups/SN/snana/SNANA_TESTS/logs/REF_20210701-1604_kess/RUNJOBS_CPU000.BATCH
and it doesn't work.

**Comment by heather999** [comment]
What happens when you try it?  
To reproduce would I just run that same script but just change the logfile? /global/cfs/cdirs/lsst/groups/SN/snana/SNANA_TESTS/logs/REF_20210701-1604_kess/RUNJOBS_CPU000.BATCH

**Comment by RickKessler** [comment]
whoops, I accidentally clobbered the batch file above. To reproduce the error,

cd /global/cfs/cdirs/lsst/groups/SN/snana/SNANA_TESTS/logs/TEST_20210701-2000_kess
sbatch RUNJOBS_CPU000.BATCH 

sbatch: error: Cannot submit batch jobs to interactive.
sbatch: error: Batch job submission failed: Unspecified error

**Comment by heather999** [comment]
Hi @RickKessler Right, the interactive queue works a little differently. You would need to use `salloc` to gain access to your node(s) and then run a script which really is just making an `srun` call.  The salloc command is going to accept parameters much like your SBATCH directives in the batch file you have:
`salloc -q interactive -A m1727 -L SCRATCH -N 1 -C haswell -t 01:00:00  --mem-per-cpu=2000`
Then once the node is allocated, you can submit your command:
`/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/SNANA_code_tests.py --test --cpunum 1  --logdir  mylog.log`
You could reconfigure your batch file to do that salloc and then submit your command so it's just one script like you have now.  It'll probably require a little more thought to do the number of jobs you're talking about - but maybe that's a start?  You could have sequential jobs if they're all fast enough but that might be wasteful as you have at least one full node allocated for those 4 hours. You could try to be a little more clever and see about using srun to submit a bunch of parallel jobs that utilize the node and the available time.
