### ISSUE TITLE
[NERSC] WL Data Storage

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#67]
**Description**
WL has a large amount of data that would be beneficial to make available under the `shared` area. [Ongoing Slack discussion](https://lsstc.slack.com/archives/C2LDMAFHC/p1619206596019100).  This issue will hopefully allow us to clearly identify the data to be moved and come to an agreement on the location under `shared`.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [x ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by liuxx479** [comment]
Please transfer these 4 sets of simulations (actual size of the folder may be smaller.. I recently cleaned up some of the files that do not need to be stored permanently):

kappaTNG 6.4TB - kappa maps with baryonic effect, based on IllustrisTNG
BAHAMAS 4.1TB - kappa maps with varying baryonic effect, based on BAHAMAS
MassiveNuS 6.5TB - correlated kappa maps and CMB lensing maps, varying neutrino mass
SLICS 2.1TB - kappa maps with varying dark energy, includes photo-z error

MassiveNuS is the folder "**convergence_6redshifts**"
all should be under `/global/cfs/cdirs/desc-wl/projects/wl-massmap`

**Comment by heather999** [comment]
Thank you @liuxx479!  If I am following the Slack discussion, we could move 
`/global/cfs/cdirs/desc-wl/projects/wl-massmap/SLICS` => `/global/cfs/cdirs/lsst/shared/external/SLICS`
`/global/cfs/cdirs/desc-wl/projects/wl-massmap/convergence_6redshifts` => `/global/cfs/cdirs/lsst/shared/external/?`  Do you want to retain the `convergence_6redshifts` as the name or call this `MassiveNuS`? Or create another subdirectory, `MassiveNuS/convergence_6redshifts`?

Joachim had mentioned on Slack: 

> a lot of out current simulation data comes from simulations external to DC2, including the MassiveNuS, the SLICS, and many hydrosims. According to your categories, these most likely fall in the “external” categories. On top of this, the WL-massmap group also have some ongoing data productions based on either to DC2 of SkySim5000. Perhaps these better fall under the DC2 umbrella?

I'm thinking kappaTNG and BAHAMAS are also considered external data and are not part of these ongoing data productions?  If so, then they would also be moved to `/global/cfs/cdirs/lsst/shared/external`

We can always modify things after the move too.

**Comment by liuxx479** [comment]
Thank you @heather999 ! Yes please move all 4 sets of simulations (SLICS, massivenus,  kappaTNG, and BAHAMAS) to /global/cfs/cdirs/lsst/shared/external. 

For massivenus, please create another subdirectory, such that: `MassiveNuS/convergence_6redshifts`
(because MassiveNuS officially has more than just the convergence maps).

After you move, could you please also create a symlink for all 4 simulation sets? such that we don't break people's code by changing the locations of the sims.

Thank you again!

**Comment by heather999** [comment]
@liuxx479 I'm ready to move the data, but I need the permissions on the directories and files to be set so that our collaboration account, "desc" can move the files.  Can you please do the following?

```
chgrp -R lsst /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/BAHAMAS
chmod -R g+rw /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/BAHAMAS
chgrp -R lsst /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/SLICS
chmod -R g+rw /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/SLICS
chgrp -R lsst /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/convergence_6redshifts
chmod -R g+rw /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/convergence_6redshifts
chgrp -R lsst /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/kappaTNG
chmod -R g+rw /global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/kappaTNG
```

**Comment by heather999** [comment]
I've updated the permissions and started to move these directories.  `SLICS` is complete and is now in: `/global/cfs/cdirs/lsst/shared/external/SLICS`  Once all the moves are complete, I will double check the permissions. Everyone on DESC with a NERSC account should have read access.

**Comment by heather999** [comment]
`BAHAMAS` and `kappaTNG` have finished moving. Still waiting for `MassiveNuS` to complete

**Comment by heather999** [comment]
All of the the transfers are complete and your data is available under:
`/global/cfs/cdirs/lsst/shared/external`  Please let me know if you have any trouble accessing it!

Now that this part is complete - @JoanneBogart @yymao do we want to talk about possibly making this accessible via GCRCatalogs?

**Comment by heather999** [comment]
I think we need to coordinate this with the WL group.  I'm guessing this is just registration.  @liuxx479 @EiffL do you have any suggestions for at least registering these datasets in GCR?

**Comment by EiffL** [comment]
Hi everyone, yeah I don't think there is any need for a reader. At least not yet, so just cataloging that these datasets are available should be enough
