### ISSUE TITLE
[NERSC] Copy redmapper v0.8.1 catalogs from cosmodc2 and dc2 dr6 to shared data.

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#68]
**Description**
A clear and concise description of what the issue is.  

I have a new version of the redMaPPer catalog from cosmodc2 v1.1.4 that fixes a small issue in v0.8.0 that affected high redshift clusters. I'm also releasing the lambda>5 catalog for easier cross-matching.  I also have, for the first time, a corresponding catalog for DC2 DR6 that calibrates the flux error problems from the image processing.

The cosmodc2 files currently here:
/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.8.1_lgt05_catalog.fit
/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.8.1_lgt05_catalog_members.fit

Should be copied to:
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmapper_v1.1.4/

The dr6 files currently here:
/global/cscratch1/sd/erykoff/cosmodc2/dc2_dr6_run_redmapper_v0.8.1_lgt20_vl50_catalog_members.fit
/global/cscratch1/sd/erykoff/cosmodc2/dc2_dr6_run_redmapper_v0.8.1_lgt20_vl50_catalog.fit

Should be copied to here: (note this is a new directory):
/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/redmapper/dr6-wfd/

I will make a PR to gcr-catalogs to make these catalogs available when they are transferred.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Transfers complete. Thanks for mentioning when there's a new directory - that makes it even easier!
Just let me know if anything is amiss.

**Comment by erykoff** [comment]
Looks great! Thanks!
