### ISSUE TITLE
[NERSC] Need set up for running LSST alerts

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#73]
**Description**
A clear and concise description of what the issue is.  

Need help to import these packages on Cori for writing LSST alerts
import lsst.alert.packet                                                       
from fastavro import writer, reader     
(ideally, part of /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh)
                                       
Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by RickKessler** [comment]
I ran "setup_sn_some.sh" and was able to run the above test script. I think this temporary setup will be ok for this broker test to write alerts. Longer term, however, we will need "data-access" tools that work with SNANA and other analysis codes.

**Comment by heather999** [comment]
@RickKessler do we want to try again to have you attend an upcoming DESC CO meeting - we meet this Wednesday, Nov 3rd at 9:10 AM PT and then every other Wednesday?  Or we could try to chat about environments and data access at an upcoming TD session?

**Comment by RickKessler** [comment]
yes, I can attend the Wed CO meeting.
