### ISSUE TITLE
[NERSC] Install PZ-RAIL

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#76]
**Description**
A clear and concise description of what the issue is.  

install PZ-RAIL in SN-setup: includes photo-z and qp codes.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

Install https://github.com/LSSTDESC/RAIL/tree/master/examples/goldenspike
as part of
   /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh

**Comment by heather999** [comment]
Looks like the most recent tagged release is 0.95: https://github.com/LSSTDESC/RAIL/tags
and that corresponds to the last commit on master branch - so that's the version I'll install, which will also install qp for us.

**Comment by heather999** [comment]
Coming back to this....  I found that PZ-RAIL and its dependencies are not compatible with the current sn-py environment.  I need to set up a sn-py-dev environment and add these additional packages so we can move forward.

**Comment by heather999** [comment]
Still stuck for now due to qp's request for astropy<5.  The current LSST Sci env uses astropy 5.0.3.  I've opened an [issue on the qp repo ](https://github.com/LSSTDESC/qp/issues/71)and I suspect we'll get this sorted out.

**Comment by heather999** [comment]
Additional issues with RAIL + qp associated with scipy >= 1.8 which is used in the LSST Sci Pipelines
