### ISSUE TITLE
[NERSC] install george

### ISSUE THREAD

**Issue by helenqu** [LSSTDESC/desc-help#77]
**Description**
I'm using the `/global/common/software/lsst/common/miniconda/sn-py` conda environment in order to use Pippin at NERSC. In order to run the SCONE classifier (one of the classification options in Pippin), the `george` gaussian process regression package is needed.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [x] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Hi @helenqu & @RickKessler Just want to confirm that this is the `george` package you want installed: https://george.readthedocs.io/en/latest/

**Comment by helenqu** [comment]
@heather999 exactly! thanks!

**Comment by helenqu** [comment]
@heather999 it works, thank you so much! now the program is breaking because it also requires `astropy` -- so sorry, should have compiled a list of requirements beforehand, but could you install that as well?

**Comment by RickKessler** [comment]
there are lots of SNANA scripts that use astropy, so it should be there in the default SN-setup ??

**Comment by heather999** [comment]
@helenqu @RickKessler astropy is indeed in the environment, but I was fiddling with RAIL earlier and that may have impacted Helen.  
Can you try again and if the problem persists, share the error you see and what command(s) you used to produce the error?

**Comment by helenqu** [comment]
@heather999 i'm running `python /global/homes/h/helenqu/scone/create_heatmaps_job.py --config_path /global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/model_config.yml --start 32 --end 50` in a batch job (`sbatch /global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/create_heatmaps__1.sh`). this `python .../create_heatmaps_job.py ...` works on the command line but errors out asking for astropy when i submit it as a job.

the traceback is 
```Traceback (most recent call last):
  File "create_heatmaps_job.py", line 6, in <module>
    from create_heatmaps.manager import CreateHeatmapsManager
  File "/global/u1/h/helenqu/scone/create_heatmaps/manager.py", line 1, in <module>
    from create_heatmaps.heatmaps_types import CreateHeatmapsFull, CreateHeatmapsEarlyMixed, CreateHeatmapsEarly, MagById, SaveFirstDetectionToCSV
  File "/global/u1/h/helenqu/scone/create_heatmaps/heatmaps_types.py", line 3, in <module>
    from create_heatmaps.base import CreateHeatmapsBase
  File "/global/u1/h/helenqu/scone/create_heatmaps/base.py", line 4, in <module>
    from astropy.table import Table
ModuleNotFoundError: No module named 'astropy'
```

**Comment by heather999** [comment]
Hi @helenqu I don't have permissions to view `/global/homes/h/helenqu/scone/create_heatmaps_job.py` 
Can you copy it to your $CSCRATCH and set permissions by doing:
```
chgrp lsst $CSCRATCH/create_heatmaps_job.py
chmod g+rx $CSCRATCH/create_heatmaps_job.py
```

**Comment by heather999** [comment]
When you run interactively, you have set up the environment using
`/global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh`
when you submit the batch job using: `sbatch /global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/create_heatmaps__1.sh`
I don't see where you are setting the environment for sn-py, I"m guessing that is the problem

```
#!/bin/bash
#SBATCH -C haswell
#SBATCH --qos=regular
#SBATCH --job-name=HELEN_CLASSIFY_MV_TRAINDES__SCONE_TRAINDES_V19__1
#SBATCH --nodes 1
#SBATCH --ntasks 18
#SBATCH --cpus-per-task 2
#SBATCH --time=00:05:00
#SBATCH --output=/global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/CREATE_HEATMAPS__model_config.yml.log

module load tensorflow/intel-2.2.0-py37
cd /global/homes/h/helenqu/scone
python create_heatmaps_job.py --config_path /global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/model_config.yml --start 32 --end 50
```

**Comment by helenqu** [comment]
I tried adding `source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh` to that sbatch file and also got the same astropy error. in the log (`/global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/CREATE_HEATMAPS__model_config.yml.log`) you can see that the line `Now using /global/common/software/lsst/common/miniconda/sn-py/bin/python` is in fact there.

i've also added the `create_heatmaps_job.py` file to $SCRATCH and followed all your instructions, so let me know if you still can't view it!

**Comment by RickKessler** [comment]
please don't source a setup in the SBATCH template file. Either source it manual, or better, add it to your .bashrc.ext so that it's automatically executed on login. When submitting jobs to batch cores, your entire environment is passed along.

**Comment by heather999** [comment]
@helenqu I think I understand why this is failing.. the python environment is changed with the
`module load tensorflow/intel-2.2.0-py37`
even though in this case attempting to load tensorflow actually returns an error (and you see that in your log too), the active version of python was updated when the script attempts to load tensorflow.  That is why astropy is not being found.
If you actually need tensorflow - we should be adding that to sn-py.

```
heatherk@cori01:/global/cscratch1/sd/heatherk/batch> source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh
Now using /global/common/software/lsst/common/miniconda/sn-py/bin/python
(base) heatherk@cori01:/global/cscratch1/sd/heatherk/batch> module load tensorflow/intel-2.2.0-py37
craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set             CRAYPE_DIR      $env(CRAYPE_DIR)

(base) heatherk@cori01:/global/cscratch1/sd/heatherk/batch> which python
/usr/common/software/tensorflow/intel-tensorflow/2.2.0-py37/bin/python
```

**Comment by helenqu** [comment]
@heather999 thanks for tracking down the problem! 

i do need both tensorflow-gpu and tensorflow-cpu. usually when i run SCONE separately from Pippin I use the `tensorflow/intel-2.2.0-py37` and `tensorflow/gpu-2.2.0-py37` modules provided by NERSC, so that's why i loaded those in my shellscript. those environments with the addition of astropy and george will successfully run SCONE.

**Comment by helenqu** [comment]
@heather999 let me know if you need any more from me!

**Comment by heather999** [comment]
@helenqu Thank you for reaching out - I need to set up a new environment that includes tensorflow.  I will try to get this set up this week.

**Comment by helenqu** [comment]
thank you so much, @heather999!

**Comment by heather999** [comment]
@RickKessler @gnarayan I'd like to understand better the conda environment needs for TD/SN.
I worked with Rick to base the conda environment on the LSST Sci Pipelines environment for the SN setup [as noted here.](https://github.com/LSSTDESC/desc-help/issues/78)
I have been thinking you want one environment for everything, including this request for george, tensorflow, etc which require MPI.  That gets a little more complicated at NERSC where we need to set up MPI using the cray mpi libraries that are available.  I'm having some trouble with that and am working to sort that out... in the meantime - is it feasible to have a separate conda environment that supports packages that require MPI?  Do you really need one environment that handles every possible case for SN?  I realize it would be easier from a user setup perspective but that's a separate question.
To get Helen going - I can set up an environment without the LSST Sci Pipelines very easily using NERSC's cray MPI libraries which is required.

**Comment by RickKessler** [comment]
to get going quickly, a temporary setup for MPI is ok. But eventually we want to run a pipeline using all of the codes, and hopefully we can avoid code-dependent setups.

**Comment by heather999** [comment]
Actually I think I have MPI at NERSC with the LSST Sci Pipelines sorted out now.  I've added in tensorflow & george and now adding PZRail and should have something for you guys to test shortly.

**Comment by heather999** [comment]
Hi @helenqu @RickKessler  Sorry for the long delay - I had to work out getting MPI set up correctly using the NERSC cray-mpich libraries.  But.. now I think it's all working with an environment that includes george and tensorflow (which includes gpu and cpu) as well as the LSST Sci Pipelines v23.0.0  (which is equivalent to w_2021_40, but is the release tag). 
To try this out, there is a new `/global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all_test.sh` script available.  You can just do:
`source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all_test.sh` and your environment will be set up with a new conda environment that should be ready to use.

I've done some limited checks:
* snana builds and I can run snana.exe and receive the expected error message if no valid input file is offered
* importing tensorflow works

Please try out this new setup_sn_all_test.sh script and report any issues that come up.  I'm hoping this can become the new baseline SN environment and we can work to keep it up to date as new packages and versions are needed by the TD group.

What's missing is PZRAIL (which I don't think Helen needs, but Rick requested).. there are specific issues there that need to be worked out with the developers.  Once that's sorted out, I'm hoping it can be installed as well.

**Comment by helenqu** [comment]
hi @heather999! thanks for putting this together! 

for the most part things seem to be working (with tensorflow-cpu), but I got a few non-fatal errors:

`ModuleCmd_Switch.c(179):ERROR:152: Module 'PrgEnv-intel' is currently not loaded`

```
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2048 current, 513038 max
```

the output log is here `/global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/CREATE_HEATMAPS__model_config.yml.log` and I'm running the same sbatch command as before (`sbatch /global/cscratch1/sd/kessler/PIPPIN_OUTPUT/HELEN_CLASSIFY_MV_TRAINDES/3_CLAS/SCONE_TRAINDES_V19/create_heatmaps__1.sh`)

**Comment by RickKessler** [comment]
the test setup works ok for me, and I didn't get error messages.

**Comment by helenqu** [comment]
I added `source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all_test.sh` to my bashrc so that my sbatched jobs would be able to use the environment, but it runs every time I run a shellscript or open a new pane in tmux. Is this necessary or is there an alternative I missed?

**Comment by heather999** [comment]
HI @helenqu Going back to your[ first comment](https://github.com/LSSTDESC/desc-help/issues/77#issuecomment-1047407806)
`ModuleCmd_Switch.c(179):ERROR:152: Module 'PrgEnv-intel' is currently not loaded` is not a problem at all, it's just a warning, but I understand it can be annoying and concerning!  I can update the script to check to see what is in the current environment - and act accordingly.. another option is to completely purge the environment and start over.  I'm not sure yet what is best but will look at that.  For now though, it's safe to ignore.

Concerning the OpenBLAS error, one way to eliminate that error is to set 
`export OPENBLAS_NUM_THREADS=1` but I suspect that might impact performance.  It might be worth playing around with that environment variable.  Sorry it took so long to respond - I think the log file and submission script have disappeared.  If you generate them again - maybe copy them to your $CSCRATCH so I can take a look.  To get a better handle on it, I'd probably need to try submitting a similar job.

To [answer your question](https://github.com/LSSTDESC/desc-help/issues/77#issuecomment-1011308575) from yesterday - I might disagree with part of [Rick's advice](https://github.com/LSSTDESC/desc-help/issues/77#issuecomment-1011308575) and suggest you really don't want to add these setup scripts to your .bashrc or .bashrc.ext - unless you want this environment for everything you do at NERSC.  It would be better to have a single script that both calls  `source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all_test.sh` and then makes the sbatch call.

**Comment by helenqu** [comment]
hi @heather999 -- sorry for the delay!
I ran source `/global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh` and got this message:
```PrgEnv-gnu/6.0.10(235):ERROR:105: Unable to locate a modulefile for 'udreg'
PrgEnv-gnu/6.0.10(235):ERROR:105: Unable to locate a modulefile for 'ugni'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'dmapp'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'gni-headers'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'xpmem'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'job'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'dvs'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'alps'
PrgEnv-gnu/6.0.10(53):ERROR:105: Unable to locate a modulefile for 'rca'
-bash: unset: `GNU8.1_LIBSCI': not a valid identifier
Setting up TD env with LSST Science Pipelines
Could not find conda environment: lsst-scipipe-0.7.0
You can list all discoverable environments with `conda info --envs`.

If 'setup' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf setup
```

however, my bash prompt shows a conda environment called `lsst-scipipe-w_2022_10`, which seemed right, so i tried running Pippin (`/global/homes/h/helenqu/Pippin/pippin.sh /global/homes/h/helenqu/Pippin//pippin_config_des/helen_pippin_config/helen_classify_MV_traindes.yml`) and it could not find the `yaml` package.

**Comment by heather999** [comment]
@helenqu Can I trouble you to try this again with either `/global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh` or `/global/cfs/cdirs/lsst/groups/TD/setup_td.sh` ?
