### ISSUE TITLE
Need f90nml package in SN setup

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#79]
**Description**
A clear and concise description of what the issue is.  

For SN setup, please note SNANA python requirements here:
     /global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/requirements.txt 
[please install f90nml ASAP since nobody can submit SNANA jobs now]

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
@RickKessler I have installed `f90nml` into both the current "production" environment set up via `source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all.sh` and in the new test environment which can be set up via `source/global/cfs/cdirs/lsst/groups/SN/software/setup_sn_all_test.sh`

Just let me know if anyone experiences any trouble.  

One more question while I have you there - thinking back to the DIA discussion yesterday, is there a need to use the same version of LSST Sci PIpelines that is ultimately chosen for the DIA processing in this SN environment?  Right now we're on `w_2021_40` basically equivalent to the v23 release and I recall DIA may be targeting `w_2021_52` or `53`).

**Comment by RickKessler** [comment]
The f90nml install seems to be working. I don't quite follow the question about LSST SciPipe versions. On a related note, how difficult would it be to install git-tagged SNANA versions as part of CVMFS (once every few weeks) to provide a more stable version that compliments the frequently changing version we have now?

**Comment by heather999** [comment]
We now have the td_env, and I think we're all set for now.
