### ISSUE TITLE
[NERSC] Copy redmagic v0.8.1 catalogs from cosmodc2 and dc2 dr6 to shared data.

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#80]
**Description**
A clear and concise description of what the issue is.  

I have new redmagic catalogs from cosmoDC2 v1.1.4 and DC2 DR6.  There will be a PR to gcr catalogs to allow access to these catalogs, but before then they need to be copied to the shared space.

The cosmodc2 files are currently here:
/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.8.1_redmagic_highlum-chi.fit
/global/cscratch1/sd/erykoff/cosmodc2/cosmoDC2_v1.1.4_mag_run_redmapper_v0.8.1_redmagic_highdens-chi.fit

And should be copied to here (this is a new directory):
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmagic_v1.1.4/

The DC2 DR6 files are currently here:
/global/cscratch1/sd/erykoff/dc2_dr6/redmapper/dc2_dr6_run_redmapper_v0.8.1_redmagic_highlum-chi.fit
/global/cscratch1/sd/erykoff/dc2_dr6/redmapper/dc2_dr6_run_redmapper_v0.8.1_redmagic_highdens-chi.fit

And should be copied to here (this is also a new directory):
/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/redmagic/dr6-wfd/

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
HI @erykoff Just want to confirm the directories to copy into, above I see:
` /global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/redmagic_v1.1.4/`
and
` /global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/redmagic/dr6-wfd/`

so the 2nd directory path has `redmagic` rather than `redmagic_v1.1.4` (which might be what you want, but I just want to make sure!)

**Comment by erykoff** [comment]
The 1.1.4 refers to the cosmodc2 version, so is only appropriate for the cosmodc2 catalog.

I'm not sure if it's the best directory naming convention, but it's what we used for redmapper so I'm just replacing redmapper with redmagic.

Thanks!

**Comment by heather999** [comment]
Ok done  - just let me know if anything looks incorrect!

**Comment by erykoff** [comment]
The cosmodc2 catalogs look good, but I'm not seeing the directory `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/redmagic/dr6-wfd/`.

**Comment by heather999** [comment]
Ah sorry.. I had mistakenly put it under cosmodc2..  moved, now it is here:
`/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/redmagic/dr6-wfd/`
look better?

**Comment by erykoff** [comment]
All fixed!
