### ISSUE TITLE
Request to have `ipdb` package at TD environment [NERSC]

### ISSUE THREAD

**Issue by BrunoSanchez** [LSSTDESC/desc-help#81]
**Description**
A clear and concise description of what the issue is.  

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [X] Cori interactive command line
- [ ] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
@BrunoSanchez Now available in the TD dev environment (which will soon become the "stable" environment).  You can try it out by doing: `source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh`

**Comment by heather999** [comment]
Should be all set in the td_env environment
