### ISSUE TITLE
[NERSC]

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#85]
**Description**
A clear and concise description of what the issue is.  
Random batch jobs disappear from queue without doing anything. 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [x ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

source /global/cfs/cdirs/lsst/groups/TD/setup_td.sh
cd $TD/SN/SNANA/SURVEYS/LSST/ROOT/ELASTICC/makeAlerts
./RUN1.sh

This problem happened yesterday with simulations, and again today with makeAlert jobs for ELASTICC. Both Rob Knop and myself had the same problem.

**Comment by heather999** [comment]
Hi @RickKessler 
Sorry for the delay.  Is this still happening? So some jobs run and complete and others disappear from the queue before ever starting up?

**Comment by RickKessler** [comment]
That pathology above only happened the day I submitted this issue. Rob Knop  & I both submitted a job today to make alerts for a full 100% ELASTICC sample ... the jobs ran for many hours and then a few batch jobs died mysteriously. Rob submitted a NERSC ticket a few hours ago [NERSC INC0188052] and they have an interesting response suggesting interference from another job that used too much memory.
