### ISSUE TITLE
utility to make home dir readable to DESC collaborators

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#86]
**Description**
A clear and concise description of what the issue is.  

need a script-utility to make our home directory readable to all LSST-DESC members. Default permissions don't allow read, which has caused many problems. Could be a stand-alone script, or an option on existing script, e.g. 
  source /global/cfs/cdirs/lsst/groups/TD/setup_td.sh  --home_readable
where a new user would include the home_readable argument only one time.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
@RickKessler that should be possible.  One tweak I might suggest, if we have people who are working on projects outside DESC or are just privacy minded- some may prefer to create a dedicated $$HOME/desc subdirectory that is readable by all DESC members rather than opening up their entire $HOME.
Would that be ok as a default?

**Comment by RickKessler** [comment]
Unprotecting $HOME/desc seems reasonable. What happens if there is no /desc dir ... is it automatically created?

**Comment by heather999** [comment]
yes exactly - if $HOME/desc doesn't exist, it should be created by the script.

**Comment by RickKessler** [comment]
ok, creating $HOME/desc sounds reasonable. People will sometimes rsync files to $HOME, then move it to $HOME/desc, so the original $HOME  protections will be kept.

**Comment by cwwalter** [comment]
Just a suggestion. I think it is fine to have  $HOME/desc as a default if you want but I for example would use like to open up $HOME.

So, I would appreciate a way to choose that.  I had a hard time when I tried to use the ACL system to do this before. Maybe a choice in the script

1) $HOME
2) $HOME/desc
3) another path

?

**Comment by RickKessler** [comment]
how about two different options:
--home_readable
--home_desc_readable

**Comment by RickKessler** [comment]
Any progress on this issue?
