### ISSUE TITLE
[NERSC] rubin_sim and DESC environments

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#88]
The LSST MAF (now [legacy_sims_maf](https://github.com/lsst-sims/legacy_sims_maf)) is now replaced with [rubin_sim](https://github.com/lsst/rubin_sim ) and I'm trying to figure out whether it is something that's already installed in the DESC stack or not. In either case, we (for the DESC OSWG) want to have an option to just run rubin_sim and another for the case where someone wants to make changes (in which case they would have to fork the repo and install it). Since there's data download involved, I think it might be nice if we can avoid multiple DESC users installing the same data over and over - but I understand that that may be unavoidable; it would be good to have some documentation though to help guide folks.

Its possible that the new stack is already installed and just the documentation needs to be created or highlighted. I'd appreciate some help in understanding where we are with rubin_sim and DESC environments on NERSC.

--

p.s. I really appreciate that I can load the old stack via
```
shifter --image=lsstdesc/stack-jupyter:w_2021_03-sims_w_2021_03-v3 /bin/bash
source /opt/lsst/software/stack/loadLSST.bash
setup lsst_distrib
setup lsst_sims
```
and add my local paths for `sims_maf` and `sims_maf_contrib` for pulling local changes. Basically what I'd like is to have something of the sort for rubin_sim.

**Comment by heather999** [comment]
Hi @humnaawan This has been on the list for awhile.  I need to go ahead and get rubin_sim added into some version of the desc stack.  I'll try to get something going that you can try out in the next week.

**Comment by humnaawan** [comment]
hi @heather999 i wanted to follow up to see if there are any update on this front?

**Comment by humnaawan** [comment]
@heather999 sorry to be a pain but I wanted to ping re this again - it'd be particularly useful to know if this is something that can be available via by the Sprint Week.

**Comment by heather999** [comment]
Hi @humnaawan No worries - just many things happening.  Yes, that is a perfect goal.. Sprint Week.  I will target getting something to you by next Wednesday Oct 12th so there is some time to test things out.

**Comment by humnaawan** [comment]
thanks so much!

**Comment by heather999** [comment]
@humnaawan Now a couple of questions:
* Do you have any simple test that uses rubin_sim?
* Re-reading your original post on this issue - do you want/need rubin_sim in the same environment as the LSST Sci Pipelines? So that you load `desc-stack` and  you have both available?  Or is it fine to just have rubin_sim as a separate environment?

**Comment by heather999** [comment]
I was able to add rubin_sim to the LSST Sci Pipelines env for the most recent weekly w_2022_42 and things seem to work.  
I found the rubin_sim_notebooks repo and am using that to test.
 https://github.com/lsst/rubin_sim_notebooks/blob/main/maf/tutorial/01_Introduction_to_MAF.ipynb

I'm going to release a new desc-stack-weekly and desc-stack-weekly-latest that includes this most recent LSST Sci Pipelines weekly and rubin_sim release (0.13.0).
Going forward, I'll try to get this automated so that desc-stack-weekly-latest continues to be updated each week and we'll keep desc-stack-weekly a week behind so it's easy to switch back if needed.

**Comment by humnaawan** [comment]
hi @heather999 thanks so much - this is great! I dont have my own tests but yeah, being able to run some of the notebooks would be the way to go for now.

For streamlining, it'd great to have both the LSST science pipes and `rubin_sim` so your plan sounds great. And having one current and one slightly old version also sounds great in case new `rubin_sim` updates break things.

Very much looking forward to stress testing this a little next week - and get people using the new framework!

**Comment by humnaawan** [comment]
re documentation: can we add some details re how one can use the framework (is it as simple as loading the stack and importing it?) + what will need to be done if you want to contribute/use it in dev mode?

**Comment by heather999** [comment]
`desc-stack-weekly` and `desc-stack-weekly-latest`have both been updated.  I have downloaded the rubin_sim data and stored it on CFS - we use rubin_sim env variable to point to this area, so everyone will have access to the same set of data.  This required a one line modification to the set up script. So no one will need to download rubin_sim data at NERSC.

To use this updated version of these jupyter kernels/conda environments will require re-running the NERSC DESC Jupyter setup:
`source /global/common/software/lsst/common/miniconda/kernels/setup.sh`
That will update your jupyter kernels in your $HOME to make sure desc-stack-weekly and desc-stack-weekly-latest use the correct setup script.
  
Concerning documentation - I need to add some new words about rubin_sim, and point to the data download mentioned above and mention the rubin_sim documentation. Truly once someone sets up `desc-stack-weekly`, all they have to do is import rubin_sim and they are all set to go.  
We'll need to test things out for "dev mode".  I think this is a good time to finally put out some suggestions so people can have some confidence about what to do.

I"ll make this my mini-sprint :)

**Comment by humnaawan** [comment]
hi @heather999 has there been progress on this front? sorry I didnt get to this during sprint week last week - but I can work on it next week and I wanted to check in with you.

I think we need a development mode version ready to go by the end of next week if possible since there's plans for rubin-sims metric development the week of Nov 7.

**Comment by heather999** [comment]
Hi @humnaawan 
Have you had a chance to try either the new `desc-stack-weekly` or `desc-stack-weekly-latest` at NERSC (either at the command line on Cori or Perlmutter) or in Jupyter?  I just want to make sure it is generally working beyond what I can test.

For development - I suspect most people would appreciate having the installation native to Cori/Perlmutter rather than in a shifter container.  This makes it easier to use the local editors available on Cori/Perlmutter.  I'm going to do a local install of desc-stack-weekly. Then we just need some instructions for folks to follow so they can to check out & install the packages they wish to develop against the desc-stack-weekly environment. Do you have any more details about what type of development people may do? Are they working on a single package that is not already in desc-stack or updating an existing package that is in desc-stack?  Are people likely to want to check out multiple packages - maybe a package with many dependencies?  Do you have an example package people might be planning to develop?

**Comment by humnaawan** [comment]
hi @heather999 yes, I am able to use `rubin_sims` using the `desc-stack-weekly` kernel in jupyter! (I had to update my kernels as you mentioned).

I very much agree that shifter container would be more cumbersome; having `rubin_sims` available via `desc-stack-weekly` is just perfect.

re the development mode: I honestly wasnt thinking much about package clashes as I was mainly concerned with contributing to `rubin_sims` which requires that one forks the repo, makes changes, and issues a PR. I guess we could have vetted out instructions on how one can do this e.g. within a conda environment on desc and maybe how to enable a kernel in jupyter so you can run your own version of `rubin_sims` in jupyterlab?

**Comment by humnaawan** [comment]
I wanted to mention that I've put together [some guidelines for OS work on NERSC](https://docs.google.com/document/d/1rQB76P_B1ONVSmnHYKXFNM1oB5IgdPD6aJ4qU-6kEnk/edit?usp=sharing). In putting this together, I noticed that there are now [guidelines](https://confluence.slac.stanford.edu/display/LSSTDESC/Setting+Up+the+DM+Stack+at+NERSC) for developing against desc-stack with rubin-sim as a working example - thank you so much! We'll test things out during the PZxOS workshop happening today.

**Comment by heather999** [comment]
Hi @humnaawan I'm sorry I haven't reached out sooner.  I have been playing with setting up a development version of rubin_sim working against my copy of desc-stack-weekly.  I'm still updating the instructions - I just added the need to update the PYTHONPATH environment variable.
I'm going to read over your instructions now and see what other things I might have missed.
Please feel free to reach out here or on Slack if you guys run into trouble during the workshop today.

**Comment by humnaawan** [comment]
thank you! ive added a note in the guidelines doc re the dev version instructions being in flux just so people have a heads-up. we'll keep you posted with any feedback.

thanks again for all this help! having rubin-sims in desc-stack is already a milestone and would very much ease analysis/development.

**Comment by heather999** [comment]
I just updated the instructions to make it a bit easier!
I'm still testing one more bit but this will hopefully get people started

**Comment by heather999** [comment]
One more missing piece is to be able to load this development environment into Jupyter..  I'll see if I can work that out.

**Comment by humnaawan** [comment]
thank you! as a temporary measure, we can import any new code in python (via `sys.path.append`) and hopefully that will work for now.

**Comment by heather999** [comment]
@humnaawan One more issue we should discuss is handling updates to desc-stack-weekly and desc-stack-weekly-latest.  These environments were meant to be updated on a weekly basis.  From one week to the next I wouldn't expect much change - but if one has rubin_sim development going on for weeks and the version of desc-stack-weekly moves 4 or 5 versions ahead from what it was when that developer started working on their copy of rubin_sim- they will likely need to redo the pip install of their local copy at least.
I can add something about this to the instructions, but also am interested in how you envision this working for most folks developing code in rubin_sim.

**Comment by humnaawan** [comment]
hi @heather999 yeah thats a good question. given that `rubin_sim` developments are not backward compatible (a lot of the times), this may become a bigger issue too even from the `rubin_sim` side.

I guess highlighting the need to redo the pip install will suffice for now. We can also point out that folks can just have a local fork of `rubin_sim`, validate it without developing against `desc-stack` (e.g. via `sys.path.append` to go to their script directly), and issue the PR from their local version. it is not ideal but it may be easier - depending on the kind of development - do avoid redoing pip installs. if however the development is s.t. that they change an existing metric/object, they might need to go via the pip install route (although you might still be able to hack things and use `sys.path` for testing). I think it'll be a minority of folks who do this kind of development though so I dont think this is of immediate concern right now.
