### ISSUE TITLE
[NERSC] CCL not loading through the desc-stack

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#9]
**Description**
I am trying to load CCL while using the `desc-stack` and it breaks the kernel on JupyterLab. I tried it while command line too and it leads to a termination of the python shell.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [x] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
Steps to reproduce the behavior on JupyterLab:
1. Load `desc-stack`
2. Run `import pyccl as ccl`
3. See the following: 
<img width="412" alt="jupyter error" src="https://user-images.githubusercontent.com/12702187/77170119-f7982680-6a90-11ea-9064-f57a51b6b6c8.png">

Steps to reproduce the behavior on command line:
1. Run `python /global/common/software/lsst/common/miniconda/start-kernel-cli.py desc-stack`
2. Create a python shell by running `python`
2. Run `import pyccl as ccl`
3. See the following: 
```
(lsst-scipipe-4d7b902) awan@cori01:~: python
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyccl as ccl
Illegal instruction
```

**Comment by heather999** [comment]
Unfortunately, I see the same problem with `pyccl` when using `desc-stack`.  It does work now with the new `desc-python`.

I'll go back over the new latest `desc-stack` release and see if I can fix it up.

**Comment by heather999** [comment]
Hi @humnaawan 
I have an updated `desc-stack-dev` that includes the latest release of CCL.  Things seem to be working now.  I'm going to promote this to prod some time today.  In the meantime, you can try this one out yourself if you have time.  Just use the `desc-stack-dev` kernel in jupyter or at the command line: `python /global/common/software/lsst/common/miniconda/start-kernel-cli.py desc-stack-dev`

**Comment by humnaawan** [comment]
@heather999 it works! thanks so much.

**Comment by heather999** [comment]
@humnaawan I just pushed this to `desc-stack` at NERSC, so now the CCL fix is in there too.
