### ISSUE TITLE
[NERSC] Copy WaZP cosmoDC2 catalogs to shared data

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/desc-help#90]
**Description**
I want to add the WaZP cosmoDC2 cluster catalogs to GCRCatalogs (see [https://github.com/LSSTDESC/gcr-catalogs/pull/601](https://github.com/LSSTDESC/gcr-catalogs/pull/601)), and need the fits files copied to the corresponding place at NERSC.

These files:
```
/global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full/wazp/6948/cosmoDC2_v1.1.4_wazp_cluster_v1.0.fits
/global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full/wazp/6948/cosmoDC2_v1.1.4_wazp_membership_v1.0.fits
```
Should be copied to:
```
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/wazp_v1.1.4/true/
``` 

and these files:
```
/global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full/wazp/6980/cosmoDC2_v1.1.4_wazp_cluster_v1.0.fits
/global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full/wazp/6980/cosmoDC2_v1.1.4_wazp_membership_v1.0.fits
```
Should be copied to:
```
/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/wazp_v1.1.4/flexzboost/
``` 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi @m-aguena Happy to help with this.  I just need read permissions to be granted to the `lsst` group. I think you can do this by doing:
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs  [you can also run this recursively with -R - it just might take more time depending on how much is under catalogs]
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs/dc2
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal
setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full

chgrp -R lsst /global/cscratch1/sd/aguena/catalogs/dc2/cosmoDC2_v1.1.4/extragal/full/wazp
[ the time for this one also depends on how many files there are in wazp.. you could just chgrp for the 6948 and 6980 directories].

To avoid this in the future - you can setfacl to make lsst the default group for some specific subdirectories under your CSCRATCH (or even all of you CSCRATCH if that's convenient), then anytime you create a new file/directory - the lsst group will automatically have access.  Let me know if you'd like to do that and I can send along some example commands.

**Comment by m-aguena** [comment]
Thanks @heather999 ! I just changed the permissions of the repos.

**Comment by heather999** [comment]
sorry for the delay @m-aguena . I still can't see any part of that path.  I think it is due to your top level directory:

```
getfacl /global/cscratch1/sd/aguena

# file: global/cscratch1/sd/aguena
# owner: aguena
# group: aguena
user::rwx
group::---
other::---

If you do
 setfacl -m g:lsst:x /global/cscratch1/sd/aguena/
that should grant execute access to the lsst group.  If the rest of the path is set similarly - I should be able to get to the files.

```

**Comment by m-aguena** [comment]
Hi @heather999 it should be visible now:
```
getfacl /global/cscratch1/sd/aguena

# file: global/cscratch1/sd/aguena
# owner: aguena
# group: aguena
user::rwx
group::---
group:lsst:--x
mask::--x
other::---



getfacl /global/cscratch1/sd/aguena/catalogs/dc2/

# file: global/cscratch1/sd/aguena/catalogs/dc2/
# owner: aguena
# group: lsst
user::rwx
group::rwx
group:lsst:--x
mask::rwx
other::---
```

Let me know if everything is ok

**Comment by heather999** [comment]
Hi  @m-aguena 
Not working quite yet. I think you need to grant x on the catalogs directory:

setfacl -m g:lsst:x /global/cscratch1/sd/aguena/catalogs 

```
getfacl /global/cscratch1/sd/aguena/catalogs/
getfacl: Removing leading '/' from absolute path names
# file: global/cscratch1/sd/aguena/catalogs/
# owner: aguena
# group: aguena
user::rwx
group::rwx
other::---
```

**Comment by m-aguena** [comment]
Hi @heather999, 
Done! Hopefuly that is it:
```
getfacl /global/cscratch1/sd/aguena/catalogs
getfacl: Removing leading '/' from absolute path names
# file: global/cscratch1/sd/aguena/catalogs
# owner: aguena
# group: aguena
user::rwx
group::rwx
group:lsst:--x
mask::rwx
other::---
```

**Comment by heather999** [comment]
ah perfect that worked @m-aguena ! Thank you for hanging in there.  I just made the copies.  You can see the files under:
`/global/cfs/cdirs/lsst/shared/xgal/cosmoDC2/addons/wazp_v1.1.4/`
Just let me know if there's anything missing or needs to be adjusted.

**Comment by m-aguena** [comment]
Everything is ok, thanks!
