### ISSUE TITLE
[NERSC] add jax to desc-python environment

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-help#92]
**Description**
A request to add jax to desc-python.  See Slack:  https://lsstc.slack.com/archives/C2M6H2LAX/p1666124048649539

**Comment by heather999** [comment]
First question might be.. just jax or should we also pull in jaxlib?

**Comment by evevkovacs** [comment]
I only need jax, but is there a downside to including both?

**Comment by heather999** [comment]
No downside.. I believe jaxlb is installed when one installs jax anyhow.  The latest desc-python includes jax, so I think this can be closed.
