### ISSUE TITLE
[NERSC] Copy redmapper and redmagic skysim5000 1.1.1 catalogs to shared data.

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/desc-help#93]
**Description**

I have run redMaPPer and redMaGiC on skysim 5000 1.1.1, and these catalogs should be transferred to shared space.

The redMaPPer files are currently here:
/global/cscratch1/sd/erykoff/skysim_5000/catalogs/skysim_5000_v1.1.1_run_redmapper_v0.8.5_lgt20_catalog.fit
/global/cscratch1/sd/erykoff/skysim_5000/catalogs/skysim_5000_v1.1.1_run_redmapper_v0.8.5_lgt20_catalog_members.fit

And should be copied to (note this is a new directory):
/global/cfs/cdirs/lsst/shared/xgal/skysim/addons/redmapper_v1.1.1/

The redMaGiC files are currently here:
/global/cscratch1/sd/erykoff/skysim_5000/catalogs/skysim_5000_v1.1.1_run_redmapper_v0.8.5_redmagic_highdens-chi.fit
/global/cscratch1/sd/erykoff/skysim_5000/catalogs/skysim_5000_v1.1.1_run_redmapper_v0.8.5_redmagic_highlum-chi.fit

And should be copied to (note this is a new directory):
/global/cfs/cdirs/lsst/shared/xgal/skysim/addons/redmagic_v1.1.1/

I will make a PR to gcr-catalogs to make these catalogs available when they are transferred.

**Comment by heather999** [comment]
Hi @erykoff The redmapper files have been copied over.  The redmagic files need o+r permission
```
-rw-r----- 1 erykoff erykoff 1036572480 Jan 19 15:44 skysim_5000_v1.1.1_run_redmapper_v0.8.5_redmagic_highdens-chi.fit
-rw-r----- 1 erykoff erykoff  372980160 Jan 19 15:44 skysim_5000_v1.1.1_run_redmapper_v0.8.5_redmagic_highlum-chi.fit
```

**Comment by erykoff** [comment]
Are you saying that I was on the ball enough to change the mode of the directory tree and the redmapper files but then failed on the redmagic files?

Yes, yes you are.

Fixed now, sorry about that.

**Comment by heather999** [comment]
The redmagic files are now copied over too!

**Comment by erykoff** [comment]
Thank you!
