### ISSUE TITLE
running setup-td twice kills session

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#94]
**Description**
A clear and concise description of what the issue is.  

Running this command twice on Perlmutter 
   source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh
kills the session. I noticed this because each makeAlert script running in shifter has to run the td-setup, and the scripts just abort after the setup.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi Rick - working on this now. I should have a new version of setup_td_dev.sh to try out in a bit.

**Comment by heather999** [comment]
Hi @RickKessler Maybe I need a little more information.  Running setup_td_dev.sh twice on a Perlmutter login node exists gracefully, but with a note that we have already run the set up - so it doesn't need to be run again.  If setup_td_dev is run again - I'm hoping it truly does nothing.  
In this case, can you describe what makeAlerts does?  It's running in shifter already, using the td_env shifter? Is it calling setup_td_dev.sh and then starts up shifter which is also calling setup_td_dev?

**Comment by RickKessler** [comment]
to see the makeAlerts problem:
cd /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/kessler/makeDataFiles_devel/LSST_ALERTS_SHIFTER/SCRIPTS_MKDATA
./test.cmd

and note these few script lines:
echo 'Setup SNANA for docker' 
source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh
echo ' ' 
echo 'Begin CPU0000_JOBLIST_login25.CMD' 

The first echo statement appears, but the echo after the setup_td does not appear because the setup_td_dev script somehow causes the test.cmd script to exit. 

I also noticed that running setup_td_dev.sh twice on the command line causes the ssh session to exit, so perhaps fixing this latter issue might also fix the makeAlert issue.

**Comment by heather999** [comment]
Hi @RickKessler I think this is now fixed.  setup_td_dev.sh should be ready to go.
I am also running

```
cd /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/kessler/makeDataFiles_devel/LSST_ALERTS_SHIFTER/SCRIPTS_MKDATA
./test.cmd
```
and it's proceeding nicely I think.  I can kill it.


Next up - I'm going to bring the updates to include cosmosis & firecrown into the dev environment so that will be done.

**Comment by heather999** [comment]
This is now really fixed :)
