### ISSUE TITLE
Please update SNANA_SCRATCH in setup-td on Perlmutter

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#95]
**Description**
A clear and concise description of what the issue is.  

In /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh,
please replace ENV SNANA_SCRATCH=/pscratch/sd/k/kessler
with SNANA_SCRATCH=/pscratch/sd/d/desctd 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Thanks for the precise reminder of what to change!  This should be done now for setup_td_dev.sh

**Comment by heather999** [comment]
This is done and released in td_env v0.0.5
