### ISSUE TITLE
add environment variables $SCONE_DIR and $SNN_DIR

### ISSUE THREAD

**Issue by helenqu** [LSSTDESC/desc-help#99]
$SCONE_DIR and $SNN_DIR are needed for Pippin to interface with photometric classifiers SCONE and SuperNNova (SNN).

please add
```
export $SCONE_DIR=/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/classifiers/scone
export $SNN_DIR=/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/classifiers/SuperNNova
```
to the desc setup script.

thank you!

**Comment by heather999** [comment]
Hi @helenqu After chatting with Gautham, we agree the location on CFS is fine.  I've updated all the setup scripts (setup_td_int.sh, setup_td_dev.sh, and setup_td.sh) to add both $SCONE_DIR and $SNN_DIR.  Just let me know if it's not working as expected.

**Comment by heather999** [comment]
Going to close this as I think this is taken care of and is available in the development version of td_env and will be released in the "stable" production version soon
